-- demo of inversion using GA
local u = vec2d.new(2,1)
local z = vec2d.new(1,0)*u -- Z = e1*u (equivalent to a complex number)
--
print("u = ", u)
print()
print("ega.inv(u)   = ", ega.inv(u))
print("u*ega.inv(u) = ",u*ega.inv(u), "ega.gr0(u*ega.inv(u)) = ",ega.gr0(u*ega.inv(u)))
print("ega.inv(u)*u = ",ega.inv(u)*u, "ega.gr0(ega.inv(u)*u) = ",ega.gr0(ega.inv(u)*u))
print()
print()
print("z = ", z)
print()
print("ega.inv(z) = ", ega.inv(z))
print("z*ega.inv(z) = ", z*ega.inv(z))
