-- show a simple reflection case expansions in 3D
local u = vec3d.new(2,1,0)
local B = bivec3d.new(1,0,0) -- e23 plane
--
-- local u_para = gr1((B >> u)*inv(B))
-- local u_perp = (u ^ B)*inv(B)
local u_para_uB = gr1((B >> u)*inv(B))
local u_perp_uB = (u ^ B)*inv(B)
local u_para_Bu = gr1(inv(B)*(u<<B))
local u_perp_Bu = inv(B)*(B ^ u)
local uB = u*B
local Bu = B*u
local uB_asym = 0.5*(uB - Bu)
local uB_sym = 0.5*(uB + Bu)
local Bu_asym = 0.5*(Bu - uB)
local Bu_sym = 0.5*(Bu + uB)
local u_R1 = -gr1(B*u*inv(B))
local u_R2 = -gr1(inv(B)*u*B)
--
print("simple reflection case expansions in 3D:")
print()
print("u = ",u)
print("B = ",B)
print("uB = ",uB)
print()
print()
print("Way 1 - using uB:")
print()
print("B>>u = ", B>>u)
print("(B>>u)*inv(B) = ", (B>>u)*inv(B))
print()
print("u^B = ", u^B)
print("(u^B)*inv(B)= ", (u^B)*inv(B))
print()
print("u_para_uB = ", u_para_uB)
print("u_perp_uB = ", u_perp_uB)
print("u_R1 = u_para_uB - u_perp_uB = ", u_para_uB - u_perp_uB)
print()
print("uB_asym = ", uB_asym)
print("uB_sym = ", uB_sym)
print("(uB_asym - uB_sym)*inv(B) = ", (uB_asym - uB_sym)*inv(B))
print("gr1((uB_asym - uB_sym)*inv(B)) = ", gr1((uB_asym - uB_sym)*inv(B)))
print()
print("u_R1 = -gr1(B*u*inv(B)) = ", u_R1)
print()
print()
print("Way 2 - using Bu:")
print()
print("u<<B = ", u<<B)
print()
print("inv(B)*(u<<B) = ", inv(B)*(B>>u))
print()
print("B^u = ", B^u)
print()
print("inv(B)*(B^u) = ", inv(B)*(B^u))
print()
print("u_para_Bu = ", u_para_Bu)
print("u_perp_Bu = ", u_perp_Bu)
print("u_R2 = u_para_Bu - u_perp_Bu = ", u_para_Bu - u_perp_Bu)
print()
print("Bu_asym = ", Bu_asym)
print("Bu_sym = ", Bu_sym)
print("inv(B)*(Bu_asym + Bu_sym) = ", inv(B)*(Bu_asym - Bu_sym))
print("gr1(inv(B)*(Bu_asym + Bu_sym)) = ", gr1(inv(B)*(Bu_asym - Bu_sym)))
print()
print("u_R2 = -gr1(inv(B)*u*B) = ", u_R2)
print()