// Hand-written bindings for the PGA rigid-body physics surface:
// inertia2dp / inertia3dp plus the four free functions that build / invert /
// apply them and compute the angular acceleration in body-frame integration.
//
// Why hand-written: the Inertia* types are struct shapes (std::array<T, N>
// storage, two operator() overloads in 2dp, view() returning std::mdspan)
// that don't fit any of the bindgen's autogenerated emit paths. The four
// physics free functions take/return Inertia* so they're skipped too.
// Hand-binding here is the smallest path that exposes the full physics
// workflow to Python — same pattern as bindings_rk4_step.cpp.
//
// Surface lives under ga_py.pga (matches where vec2dp / bivec2dp /
// move2dp etc. live, even though the typedefs `inertia2dp`/`inertia3dp`
// are in `hd::ga`). See ga_bindgen/src/emit_nanobind.py::submodule_for —
// PGA primitives are routed by canonical_underlying namespace, not by
// typedef location.

#include <nanobind/nanobind.h>
#include <nanobind/operators.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/string_view.h>

#include <fmt/format.h>

#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

#include "ga/ga_pga.hpp"

namespace nb = nanobind;
using namespace hd::ga;
using namespace hd::ga::pga;

namespace {

// Index validation + element access for the typed inertia matrices.
// Indexed via a 2-tuple so Python users write `I[r, c]` (Python's subscript
// with a tuple — same pattern as numpy / mdspan).
template <typename Inertia, size_t N>
double inertia_get(Inertia const& I, std::pair<size_t, size_t> ij)
{
    auto const [r, c] = ij;
    if (r >= N || c >= N) {
        throw std::out_of_range("inertia index out of range (matrix is " +
                                std::to_string(N) + "x" + std::to_string(N) + ")");
    }
    return I.view()[r, c];
}

template <typename Inertia, size_t N>
void inertia_set(Inertia& I, std::pair<size_t, size_t> ij, double v)
{
    auto const [r, c] = ij;
    if (r >= N || c >= N) {
        throw std::out_of_range("inertia index out of range (matrix is " +
                                std::to_string(N) + "x" + std::to_string(N) + ")");
    }
    I.view()[r, c] = v;
}

// Common __format__ implementation — pipes Python f-string format specs
// through fmt::runtime to the existing fmt::formatter specialisations in
// ga/detail/fmt/ga_fmt_physics.hpp. Mirrors emit_format_lambda() in the
// bindgen so behaviour is consistent with autogenerated types.
template <typename Inertia>
std::string inertia_format(Inertia const& I, std::string_view spec)
{
    try {
        if (spec.empty()) return fmt::format("{}", I);
        return fmt::format(fmt::runtime("{:" + std::string(spec) + "}"), I);
    } catch (fmt::format_error const& e) {
        throw std::invalid_argument(e.what());
    }
}

} // anonymous namespace


void bind_physics(nb::module_& pga)
{
    // ----- inertia2dp ------------------------------------------------------
    // 3x3 inertia map for PGA2DP rigid bodies.
    //
    // Two operator() overloads (Python __call__):
    //   I(omega: vec2dp)   -> bivec2dp   (forward map: rate-of-change -> momentum)
    //   I(arg: bivec2dp)   -> vec2dp     (inverse map: momentum -> rate-of-change)
    // nanobind dispatches by argument type at call time.
    nb::class_<inertia2dp>(pga, "inertia2dp")
        .def(nb::init<>(), "Default-construct a 3x3 zero inertia matrix.")
        .def(nb::self += nb::self)
        .def(nb::self -= nb::self)
        .def("__call__",
             [](inertia2dp const& I, vec2dp const& Omega) { return I(Omega); },
             nb::arg("Omega"),
             "Forward inertia map I[Omega]: vec2dp rate-of-change -> bivec2dp momentum.")
        .def("__call__",
             [](inertia2dp const& I, bivec2dp const& F) { return I(F); },
             nb::arg("F"),
             "Inverse inertia map I_inv[F]: bivec2dp momentum -> vec2dp rate-of-change.")
        .def("__getitem__", &inertia_get<inertia2dp, 3>,
             "Read element (row, col); pass a 2-tuple, e.g. I[2, 2].")
        .def("__setitem__", &inertia_set<inertia2dp, 3>,
             "Write element (row, col); pass a 2-tuple, e.g. I[2, 2] = 8/3.")
        .def("__repr__",
             [](inertia2dp const& I) { return fmt::format("inertia2dp({})", I); })
        .def("__str__", [](inertia2dp const& I) { return fmt::format("{}", I); })
        .def("__format__",
             [](inertia2dp const& I, std::string_view spec) {
                 return inertia_format(I, spec);
             },
             nb::arg("format_spec"));

    // 2dp factory / arithmetic free functions.
    pga.def("get_point_inertia",
            [](double m, vec2dp const& X) { return get_point_inertia(m, X); },
            nb::arg("m"), nb::arg("X"),
            "Inertia of a point mass m at position X (2dp).");
    pga.def("get_plate_inertia",
            [](double m, double w, double h, vec2dp const& P_pivot) {
                return get_plate_inertia(m, w, h, P_pivot);
            },
            nb::arg("m"), nb::arg("w"), nb::arg("h"),
            nb::arg("P_pivot") = vec2dp{0.0, 0.0, 1.0},
            "Inertia of a uniform rectangular plate (mass m, width w, height h) "
            "centered at the body origin, with parallel-axis (Steiner) correction "
            "about an optional pivot P_pivot (default = body origin).");
    pga.def("get_inertia_inverse",
            [](inertia2dp const& I) { return get_inertia_inverse(I); },
            nb::arg("I"),
            "Inverse of a 2dp inertia matrix via LU decomposition. "
            "Raises ValueError if the matrix is singular.");
    pga.def("compute_omega_dot",
            [](inertia2dp const& I_inv, bivec2dp const& F,
               vec2dp const& Omega, inertia2dp const& I) {
                return compute_omega_dot(I_inv, F, Omega, I);
            },
            nb::arg("I_inv"), nb::arg("F"), nb::arg("Omega"), nb::arg("I"),
            "Right-hand side of the body-frame Euler ODE in 2dp:\n"
            "  Omega_dot = I_inv[ F - rcmt(Omega, I[Omega]) ]");

    // ----- inertia3dp ------------------------------------------------------
    // 6x6 inertia map for PGA3DP rigid bodies. In 3D both forward and
    // inverse maps are bivec3dp -> bivec3dp (a single operator() overload).
    nb::class_<inertia3dp>(pga, "inertia3dp")
        .def(nb::init<>(), "Default-construct a 6x6 zero inertia matrix.")
        .def(nb::self += nb::self)
        .def(nb::self -= nb::self)
        .def("__call__",
             [](inertia3dp const& I, bivec3dp const& Omega) { return I(Omega); },
             nb::arg("Omega"),
             "Inertia map I[Omega] (or I_inv[F] for the inverse): "
             "bivec3dp -> bivec3dp.")
        .def("__getitem__", &inertia_get<inertia3dp, 6>,
             "Read element (row, col); pass a 2-tuple, e.g. I[5, 2].")
        .def("__setitem__", &inertia_set<inertia3dp, 6>,
             "Write element (row, col); pass a 2-tuple, e.g. I[5, 2] = 8/3.")
        .def("__repr__",
             [](inertia3dp const& I) { return fmt::format("inertia3dp({})", I); })
        .def("__str__", [](inertia3dp const& I) { return fmt::format("{}", I); })
        .def("__format__",
             [](inertia3dp const& I, std::string_view spec) {
                 return inertia_format(I, spec);
             },
             nb::arg("format_spec"));

    // 3dp factory / arithmetic free functions.
    pga.def("get_point_inertia",
            [](double m, vec3dp const& X) { return get_point_inertia(m, X); },
            nb::arg("m"), nb::arg("X"),
            "Inertia of a point mass m at position X (3dp).");
    pga.def("get_cuboid_inertia",
            [](double m, double w, double h, double d, bivec3dp const& L_pivot) {
                return get_cuboid_inertia(m, w, h, d, L_pivot);
            },
            nb::arg("m"), nb::arg("w"), nb::arg("h"), nb::arg("d"),
            nb::arg("L_pivot") = bivec3dp{},
            "Inertia of a uniform rectangular cuboid (mass m, extents w x h x d) "
            "centered at the body origin, with parallel-axis (Steiner) correction "
            "about an optional pivot line L_pivot (default = body origin / no shift).");
    pga.def("get_inertia_inverse",
            [](inertia3dp const& I) { return get_inertia_inverse(I); },
            nb::arg("I"),
            "Inverse of a 3dp inertia matrix via LU decomposition. "
            "Raises ValueError if the matrix is singular.");
    pga.def("compute_omega_dot",
            [](inertia3dp const& I_inv, bivec3dp const& F,
               bivec3dp const& Omega, inertia3dp const& I) {
                return compute_omega_dot(I_inv, F, Omega, I);
            },
            nb::arg("I_inv"), nb::arg("F"), nb::arg("Omega"), nb::arg("I"),
            "Right-hand side of the body-frame Euler ODE in 3dp:\n"
            "  Omega_dot = I_inv[ F - rcmt(Omega, I[Omega]) ]");
}
