"""Emit nanobind C++ bindings from a manifest.

Two modes:
  --type NAME     Emit a single type (for quick iteration).
  --all           Emit every eligible type in the manifest plus register_all.cpp
                  and bindings_list.cmake.

Eligibility (v1): struct/class with ≥1 public T-typed field and at least one
all-T-parameter constructor (after normalizing references/const). Scalar/
PScalar types (private `value` field + explicit operator T&) are not yet
handled — deferred to a later iteration.

Usage:  python3 ga_bindgen/src/emit_nanobind.py --all
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from clang_setup import PROJECT_ROOT
from model import Manifest, TypeAlias

GA_PY = PROJECT_ROOT / "ga_py"
DEFAULT_MANIFEST = PROJECT_ROOT / "ga_bindgen" / "manifest.json"
DEFAULT_OUT = GA_PY / "src" / "generated"

GENERATED_HEADER = """\
// AUTO-GENERATED BY ga_bindgen — DO NOT EDIT.
// Regenerate via: python3 ga_bindgen/src/emit_nanobind.py --all
// Source manifest: ga_bindgen/manifest.json

#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <nanobind/operators.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/string_view.h>
#include <nanobind/stl/vector.h>
#include <fmt/format.h>
#include <array>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "ga/ga_ega.hpp"
#include "ga/ga_pga.hpp"

namespace nb = nanobind;
using namespace hd::ga;
using namespace hd::ga::ega;
using namespace hd::ga::pga;
"""


def normalize_param(p: str) -> str:
    """Reduce a parameter type spelling to its base: strip const/reference qualifiers."""
    p = p.strip()
    if p.startswith("const "):
        p = p[6:].strip()
    while p.endswith("&"):
        p = p[:-1].strip()
    return p


def base_template_name(p: str) -> str:
    """Strip const, &, namespace, and `<...>` from a param spelling.

    >>> base_template_name("const Vec3d<T> &")
    'Vec3d'
    >>> base_template_name("hd::ga::Scalar3d<T>")
    'Scalar3d'
    """
    s = normalize_param(p)
    if "<" in s:
        s = s.split("<", 1)[0].strip()
    return s.rsplit("::", 1)[-1]


_TAG_RE = re.compile(r"\b([a-z][a-z0-9_]*_tag)\b")


def build_type_name_map(types: list[TypeAlias]) -> dict[str, str]:
    """Map intermediate template alias names ('Vec3d', 'Scalar3d', 'MVec3d_E')
    to the user typedef name we bind ('vec3d', 'scalar3d', 'mvec3d_e').

    Derived from `t.underlying`, e.g. `vec3d` has underlying `Vec3d<value_t>`,
    so the entry is `Vec3d -> vec3d`.

    Additionally registers an entry keyed by the **discriminating tag** parsed
    out of `t.canonical_underlying` (e.g. `bivec2dp_tag -> bivec2dp`). This
    lets the resolver recover the typedef when libclang reports the underlying
    class template form rather than the user typedef --- which happens for
    `auto const`-deduced constants whose initializer goes through an
    operator (e.g. `auto const H_2dp = -e12_2dp;` resolves to
    `Vec3_t<double, bivec2dp_tag>`, not `BiVec2dp<value_t>`).
    """
    m: dict[str, str] = {}
    for t in types:
        # Skip uppercase template aliases --- only lowercase user types should
        # appear as the canonical bound name.
        if t.name[:1].isupper():
            continue
        head = t.underlying.split("<", 1)[0].strip().rsplit("::", 1)[-1]
        if head:
            m.setdefault(head, t.name)
        # Also key by the unique tag parsed out of the canonical form.
        tag_match = _TAG_RE.search(t.canonical_underlying or "")
        if tag_match:
            m.setdefault(tag_match.group(1), t.name)
    return m


# Primitive numeric types we accept (mapped to `double` for emission).
# These come up in functions like `nrm(Vec3d<T>) -> T`, where after T=double
# instantiation the type is just a primitive.
_PRIMITIVE_SCALAR_NAMES = {
    "T", "U", "double", "float", "value_t",
    # `std::common_type_t<T, U>` and `ctype` get reduced via base_template_name
    # (it strips the template args and namespace); both end up as bare names.
    "common_type_t", "ctype",
}

# Integer types — emitted as `int` parameters / returns. nanobind handles
# Python int <-> C++ integer conversion natively.
_INTEGER_TYPE_NAMES = {
    "size_t", "int", "long", "unsigned", "ptrdiff_t", "uint32_t", "int32_t",
    "uint64_t", "int64_t",
}

# Types that Python handles natively (bound automatically by nanobind without
# any header inclusion beyond <nanobind/nanobind.h>).
_NATIVE_NAMES = {"bool"}


def _split_template_args(inner: str) -> list[str]:
    """Split a `<...>`'s comma-separated argument list, respecting nesting.

    Plain str.split would break on `std::array<std::vector<X>, 2>` because
    the inner `<...>` itself contains a comma. Walks the string tracking
    angle-bracket depth and splits only at top-level commas.
    """
    args: list[str] = []
    depth = 0
    start = 0
    for i, ch in enumerate(inner):
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        elif ch == "," and depth == 0:
            args.append(inner[start:i].strip())
            start = i + 1
    args.append(inner[start:].strip())
    return args


def _strip_outer_template(p: str) -> tuple[str, list[str]]:
    """If `p` is `std::vector<X>` / `std::pair<X, Y>` / `std::array<X, N>` /
    `std::tuple<...>`, return the container short-name and the list of
    template arguments (already nesting-aware split).

    Returns ('', []) if `p` isn't a recognised STL container.
    """
    s = p.strip()
    # Strip leading `const ` and trailing `&`.
    if s.startswith("const "):
        s = s[6:].strip()
    while s.endswith("&"):
        s = s[:-1].strip()
    if "<" not in s or not s.endswith(">"):
        return "", []
    head = s.split("<", 1)[0].strip().rsplit("::", 1)[-1]
    if head not in {"vector", "pair", "tuple", "array"}:
        return "", []
    inner = s[s.index("<") + 1: -1]
    return head, _split_template_args(inner)


def resolve_param_to_user_type(p: str, type_map: dict[str, str]) -> str | None:
    """Resolve a C++ parameter / return spelling to a Python-bindable type id.

    Returns:
      - the user-typedef name (e.g. 'vec3d') for a bound type,
      - 'double' for primitive numeric scalars (T, double, ...),
      - 'bool' for native bool,
      - 'std::vector<X>' (literal C++ string) for a vector of bound types,
      - None if the type is not bindable.
    """
    base = base_template_name(p)
    if base in type_map:
        return type_map[base]
    if base in _PRIMITIVE_SCALAR_NAMES:
        return "double"
    if base in _INTEGER_TYPE_NAMES:
        return "int"
    if base in _NATIVE_NAMES:
        return base

    # Fallback: when libclang gives us the underlying class template form
    # (e.g. `Vec3_t<double, hd::ga::bivec2dp_tag>` instead of `BiVec2dp<...>`),
    # the discriminating tag still uniquely identifies the typedef.
    tag_match = _TAG_RE.search(p)
    if tag_match and tag_match.group(1) in type_map:
        return type_map[tag_match.group(1)]

    # Recognise STL containers of bindable element types. Each emitted
    # literal C++ type round-trips via the matching nanobind/stl/<x>.h
    # caster (vector → list, pair → 2-tuple, array → tuple, …) — all of
    # which are pulled in by GENERATED_HEADER.
    container, args = _strip_outer_template(p)
    if container == "vector" and len(args) == 1:
        elem = resolve_param_to_user_type(args[0], type_map)
        if elem is not None and elem != "bool":
            return f"std::vector<{elem}>"
    if container == "pair" and len(args) == 2:
        a = resolve_param_to_user_type(args[0], type_map)
        b = resolve_param_to_user_type(args[1], type_map)
        if a is not None and b is not None and a != "bool" and b != "bool":
            return f"std::pair<{a}, {b}>"
    if container == "array" and len(args) == 2:
        # std::array<T, N> — second argument is a non-type extent we keep
        # verbatim (nanobind needs the full type spelling at the binding
        # site, not just the element type).
        elem = resolve_param_to_user_type(args[0], type_map)
        if elem is not None and elem != "bool":
            return f"std::array<{elem}, {args[1]}>"
    return None


# Map C++ binary operator names to Python dunder names.
# Unary minus stays bound via `nb::self` (handled separately in each emitter);
# in-place ops (+=, -=, ...) and comparisons (==, !=) are also separate.
CPP_OP_TO_DUNDER = {
    "operator+": "__add__",
    "operator-": "__sub__",   # binary subtraction; unary handled separately
    "operator*": "__mul__",
    "operator/": "__truediv__",
    "operator<<": "__lshift__",
    "operator>>": "__rshift__",
}

# C++ free-function names that map to Python operator dunders.
# wedge `wdg` is exposed as Python `^`, mirroring ga_lua's choice.
FUNCTION_TO_DUNDER = {
    "wdg": "__xor__",
}

# Operator-like names we DO NOT auto-bind here (covered elsewhere or omitted).
SKIP_OPERATOR_NAMES = {
    "operator==", "operator!=",
    "operator+=", "operator-=", "operator*=", "operator/=",
    "operator<", "operator<=", "operator>", "operator>=",
}


def collect_binary_operators(manifest: Manifest,
                             type_map: dict[str, str]
                             ) -> dict[str, list[tuple[str, str, str, str, str]]]:
    """For each user type, return a list of operator method bindings.

    Each entry is `(dunder, rhs_user_type, return_user_type, callable_text, kind)`:
      - dunder: Python method name (e.g. '__add__')
      - rhs_user_type: bound Python class for the second argument
      - return_user_type: bound Python class for the result (informational)
      - callable_text: the C++ expression form to use inside the lambda body,
        e.g. '+', '*', or 'wdg' depending on whether it's an operator symbol
        or a function name
      - kind: 'op' for C++ operators, 'fn' for functions mapped to dunders
    """
    out: dict[str, list[tuple[str, str, str, str, str]]] = defaultdict(list)

    for grp in manifest.operators:
        if grp.name not in CPP_OP_TO_DUNDER:
            continue
        dunder = CPP_OP_TO_DUNDER[grp.name]
        symbol = grp.name[len("operator"):]  # '+', '*', '<<', etc.
        for ov in grp.overloads:
            if len(ov.param_types) != 2:
                continue  # skip unary minus; in-place handled separately
            lhs = resolve_param_to_user_type(ov.param_types[0], type_map)
            rhs = resolve_param_to_user_type(ov.param_types[1], type_map)
            ret = resolve_param_to_user_type(ov.return_type, type_map)
            if not (lhs and rhs and ret):
                continue
            out[lhs].append((dunder, rhs, ret, symbol, "op"))

    for grp in manifest.functions:
        if grp.name not in FUNCTION_TO_DUNDER:
            continue
        dunder = FUNCTION_TO_DUNDER[grp.name]
        for ov in grp.overloads:
            if len(ov.param_types) != 2:
                continue
            lhs = resolve_param_to_user_type(ov.param_types[0], type_map)
            rhs = resolve_param_to_user_type(ov.param_types[1], type_map)
            ret = resolve_param_to_user_type(ov.return_type, type_map)
            if not (lhs and rhs and ret):
                continue
            out[lhs].append((dunder, rhs, ret, grp.name, "fn"))

    # Dedup: keep first occurrence of each (dunder, rhs) on each lhs to
    # avoid ambiguous overloads when C++ has multiple same-arg-type
    # operators with differing return types (rare but real, see e.g.
    # `Scalar3dp + PScalar3dp` which appears as MVec3dp_E, MVec3dp, and
    # DualNum3dp).
    deduped: dict[str, list[tuple[str, str, str, str, str]]] = {}
    for lhs, entries in out.items():
        seen: set[tuple[str, str]] = set()
        kept: list[tuple[str, str, str, str, str]] = []
        for e in entries:
            k = (e[0], e[1])  # (dunder, rhs)
            if k in seen:
                continue
            seen.add(k)
            kept.append(e)
        # Reorder for dispatch performance: nanobind tries overloads in
        # registration order, so the hot path should be first within each
        # dunder bucket. Heuristic: same-type rhs first (geometric product,
        # dot, wedge of T×T are the GA hot paths), then `double` (scalar
        # mul/div), then everything else in the order the manifest scan
        # produced it. Group-by-dunder before sorting so dunder buckets
        # stay contiguous (entries from the two appender loops above are
        # already grouped: all `__add__` together, then all `__mul__`, …).
        def _rhs_rank(rhs: str) -> int:
            if rhs == lhs:
                return 0          # same-type: hottest path
            if rhs == "double":
                return 1          # scalar mul/div: very common
            return 2              # everything else: original order
        reordered: list[tuple[str, str, str, str, str]] = []
        i = 0
        while i < len(kept):
            j = i
            cur_dunder = kept[i][0]
            while j < len(kept) and kept[j][0] == cur_dunder:
                j += 1
            bucket = kept[i:j]
            bucket.sort(key=lambda e: _rhs_rank(e[1]))  # stable
            reordered.extend(bucket)
            i = j
        deduped[lhs] = reordered
    return deduped


def render_op_def(cls: str, dunder: str, rhs: str,
                  callable_text: str, kind: str) -> str:
    """Format a single .def(__op__, lambda) line for a binary operator binding.

    Direct lambda — no SFINAE/requires guard. If a manifest-listed overload
    fails to compile, that surfaces a real bug in `ga/` that should be
    fixed at the source rather than masked here.
    """
    if kind == "op":
        body = f"return a {callable_text} b;"
    else:
        body = f"return {callable_text}(a, b);"
    return (f'        .def("{dunder}", []({cls} const& a, {rhs} const& b) {{ '
            f'{body} }}, nb::is_operator())')


# Names handled elsewhere — must NOT be re-emitted as free functions.
# Note: `wdg` IS emitted as a free function `ga_py.{ega,pga}.wdg(a, b)` so
# Python code can match the C++ idiom; it ALSO has `__xor__` for users who
# prefer operator syntax (per the operator-mapping decision in §9 of the
# considerations doc).
_GRADE_EXTRACTOR_RE = re.compile(r"^gr\d+$")  # gr0, gr1, ..., grN


# Hand-curated converting constructors that the scanner cannot pick up.
#
# libclang reports constrained constructor templates (those with a `requires`
# clause) as `CursorKind.FUNCTION_TEMPLATE`, not `CursorKind.CONSTRUCTOR`, so
# the scanner skips them. Extracting the requires clause (e.g. `requires
# std::is_same_v<Tag, vec2dp_tag> && std::is_same_v<Tag2, vec2d_tag>`) to
# decide which (target, source) pair is valid would require walking the
# requires-AST. For the small fixed set of conversions in this library it is
# simpler to register them explicitly.
#
# Format: target_typedef -> list of (init_arg_python_type, ...) tuples.
# Each entry produces an extra `nb::init<arg0 const&, arg1, ...>()` line on
# the target type.
#
# When adding a new entry, also add the matching converting constructor in
# the corresponding ga/detail/type_t/ga_*_t.hpp header --- the C++ template
# instantiation is what makes the Python binding compile.
CONVERTING_CTORS: dict[str, list[tuple[str, ...]]] = {
    # vec2dp(vec2d, T) --- homogeneous extension of a 2D Euclidean point
    # (Vec3_t<vec2dp_tag>(Vec2_t<vec2d_tag>, T) in C++).
    "vec2dp": [("vec2d", "double")],
    # vec3dp(vec3d, T) --- homogeneous extension of a 3D Euclidean point
    # (Vec4_t<vec3dp_tag>(Vec3_t<vec3d_tag>, T) in C++).
    "vec3dp": [("vec3d", "double")],
}


SKIP_FREE_FN_NAMES = {
    # gr<N> per-grade extractors are bound as instance methods on multivectors
    # (see collect_grade_extractors); skipped here via _GRADE_EXTRACTOR_RE in
    # collect_free_functions, so this constant set need not enumerate them.
    #
    # Generic predicates restricted to integral types via `requires(std::is_integral_v<T>)`:
    # the resolver would emit them with `double` args which fail the constraint.
    # Python has `n % 2 == 0` natively, so no need to bind these.
    "is_even", "is_odd",
    # Internal, configuration, and false-positive cursor names that shouldn't
    # leak through. Uppercase-leading names are filtered separately.
    "abs",                        # collides with Python builtin; not a GA op
}


def collect_free_functions(manifest: Manifest,
                           type_map: dict[str, str],
                           file_filter: set[str] | None
                           ) -> dict[str, dict[str, list[tuple[list[str], str]]]]:
    """For each (submodule, function name), list bindable overloads.

    Output: {submodule_name: {fn_name: [(param_user_types, return_user_type), ...]}}
    submodule_name is one of 'ega', 'pga', 'top'.

    `file_filter` is a set of source-file basenames; only overloads declared
    in one of those files are emitted. None means no filter (emit everything).
    """
    out: dict[str, dict[str, list[tuple[list[str], str]]]] = {
        "ega": defaultdict(list),
        "pga": defaultdict(list),
        "top": defaultdict(list),
    }
    seen: set[tuple] = set()  # dedup (submodule, fn_name, param_tuple, return)

    for grp in manifest.functions:
        if grp.name.startswith("operator"):
            continue
        if grp.name in SKIP_FREE_FN_NAMES:
            continue
        if _GRADE_EXTRACTOR_RE.match(grp.name):
            # gr0/gr1/.../grN are emitted as multivector instance methods
            # by collect_grade_extractors, never as free functions.
            continue
        # Filter cursor false-positives that come from libclang reporting
        # class-template constructor-like declarations as function names
        # (e.g. "MVec8_t<T, Tag>"). Real free functions never contain `<`
        # in their name. This preserves legitimate names with leading
        # uppercase letters such as `Hz2radps`.
        if "<" in grp.name:
            continue

        # Pick destination submodule from the function's own namespace.
        if grp.namespace == "hd::ga::ega":
            submod = "ega"
        elif grp.namespace == "hd::ga::pga":
            submod = "pga"
        elif grp.namespace == "hd::ga":
            submod = "top"
        else:
            continue  # detail or other — already filtered by scanner, defensive

        for ov in grp.overloads:
            if file_filter is not None:
                src_basename = ov.source_file.rsplit("/", 1)[-1]
                if src_basename not in file_filter:
                    continue
            params: list[str] = []
            ok = True
            for p in ov.param_types:
                u = resolve_param_to_user_type(p, type_map)
                if u is None:
                    ok = False
                    break
                params.append(u)
            if not ok:
                continue
            ret = resolve_param_to_user_type(ov.return_type, type_map)
            if ret is None:
                continue
            key = (submod, grp.name, tuple(params), ret)
            if key in seen:
                continue
            seen.add(key)
            out[submod][grp.name].append((params, ret))

    # Convert defaultdicts to plain dicts for JSON-friendly output.
    return {sm: dict(fns) for sm, fns in out.items()}


def _param_decl(typename: str, idx: int) -> str:
    """Format a lambda parameter declaration. Primitive scalars (and ints/
    bool) pass by value; user types and STL containers pass by const&."""
    if typename in ("double", "int", "bool"):
        return f"{typename} a{idx}"
    return f"{typename} const& a{idx}"


def collect_constants(manifest: Manifest,
                      type_map: dict[str, str]
                      ) -> dict[str, list[tuple[str, str, str]]]:
    """For each submodule, list (constant_name, fully_qualified_cpp_name, user_typedef).

    Only constants whose type resolves through `type_map` (i.e. are a bound
    user type) are kept. Skips std::array and other unbindable types.
    """
    out: dict[str, list[tuple[str, str, str]]] = {"ega": [], "pga": [], "top": []}
    for c in manifest.constants:
        if c.namespace == "hd::ga::ega":
            submod = "ega"
        elif c.namespace == "hd::ga::pga":
            submod = "pga"
        elif c.namespace == "hd::ga":
            submod = "top"
        else:
            continue
        # Resolve the constant's type to a Python-bound user type.
        user = resolve_param_to_user_type(c.type, type_map)
        if user is None or user in ("double", "int", "bool"):
            # Skip primitive constants for now — those aren't typically
            # what users want anyway (constants like e1_2d are typed
            # objects, not raw doubles).
            continue
        if not isinstance(user, str) or user.startswith("std::"):
            continue  # vector / pair / tuple constants — unusual; defer
        # Use the fully-qualified C++ name for emission so we don't depend on
        # what `using namespace` directives are in scope.
        fq = f"{c.namespace}::{c.name}"
        out[submod].append((c.name, fq, user))
    return out


def emit_constants_module(submodule: str,
                          consts: list[tuple[str, str, str]]) -> str:
    """Emit a register_constants_<submodule>(nb::module_& m) translation unit
    that exposes each constant as a Python module attribute.

    Uses `nb::cast(value)` to construct the corresponding Python wrapper —
    nanobind copies the value, so the Python attribute is independent of
    the C++ static."""
    lines: list[str] = []
    for name, fq, _user_type in sorted(consts):
        lines.append(f'    m.attr("{name}") = nb::cast({fq});')
    body = "\n".join(lines) if lines else "    (void)m;  // no constants in this submodule yet"
    return (
        f"void register_constants_{submodule}(nb::module_& m) {{\n"
        f"{body}\n"
        f"}}\n"
    )


def emit_function_module(submodule: str,
                         fn_groups: dict[str, list[tuple[list[str], str]]]) -> str:
    """Emit a register_functions_<submodule>(nb::module_& m) translation unit
    binding all collected free-function overloads as `m.def(...)`.
    """
    lines: list[str] = []
    for fn_name in sorted(fn_groups):
        for params, _ret in fn_groups[fn_name]:
            param_decls = ", ".join(_param_decl(p, i) for i, p in enumerate(params))
            arg_list = ", ".join(f"a{i}" for i in range(len(params)))
            lines.append(
                f'    m.def("{fn_name}", []({param_decls}) {{ '
                f'return {fn_name}({arg_list}); }});'
            )

    body = "\n".join(lines) if lines else "    (void)m;  // no functions in this submodule yet"
    return (
        f"void register_functions_{submodule}(nb::module_& m) {{\n"
        f"{body}\n"
        f"}}\n"
    )


def collect_grade_extractors(manifest: Manifest,
                             type_map: dict[str, str]
                             ) -> dict[str, list[tuple[str, str]]]:
    """For each multivector user type, return a list of (method_name, return_user_type)
    derived from the gr0/gr1/gr2/gr3 overloads in the manifest.

    Example: 'mvec3d' -> [('gr0','scalar3d'), ('gr1','vec3d'),
                          ('gr2','bivec3d'), ('gr3','pscalar3d')]
    """
    out: dict[str, dict[str, str]] = {}
    for grp in manifest.functions:
        if not _GRADE_EXTRACTOR_RE.match(grp.name):
            continue
        for ov in grp.overloads:
            if len(ov.param_types) != 1:
                continue
            param_user = resolve_param_to_user_type(ov.param_types[0], type_map)
            return_user = resolve_param_to_user_type(ov.return_type, type_map)
            if not param_user or not return_user:
                continue
            out.setdefault(param_user, {})[grp.name] = return_user
    return {k: sorted(v.items()) for k, v in out.items()}


def is_scalar_shape(t: TypeAlias) -> bool:
    """Scalar_t<T, Tag>-shaped user types: private `value`, explicit T<->type
    conversion operator, no public fields. Identified by name + 0 fields."""
    if t.name[:1].isupper():
        return False
    if t.fields:
        return False
    return (t.name.startswith("scalar") or t.name.startswith("pscalar")) \
        and "Scalar_t<" in t.canonical_underlying


def is_vec_shape(t: TypeAlias) -> bool:
    """Vec_t/MVec_t/DualNum-shaped types: public T fields, all-T N-arg ctor."""
    if t.name[:1].isupper():
        return False
    if not t.fields:
        return False
    if not all(f.type == "T" for f in t.fields):
        return False
    return any(
        c.param_types and all(normalize_param(p) == "T" for p in c.param_types)
        for c in t.constructors
    )


def is_inherited_shape(t: TypeAlias) -> bool:
    """PGA geometric primitives like `Point2d : public Vec2d<T>` —
    fields are inherited from the base; the derived class adds only a few
    convenience constructors."""
    if t.name[:1].isupper():
        return False
    return t.base_class is not None


def is_eligible(t: TypeAlias) -> bool:
    """Union of supported shapes."""
    return is_vec_shape(t) or is_scalar_shape(t) or is_inherited_shape(t)


def submodule_for(t: TypeAlias) -> str:
    """Route a user type into ega or pga.

    Primary signal: presence of `pga::` in the canonical_underlying — this
    correctly catches PGA geometric primitives whose user-typedef name does
    not end in `dp` (e.g., `point2d -> hd::ga::pga::Point2d<double>`).
    Secondary: name suffix `2dp` / `3dp`.
    """
    if "pga::" in t.canonical_underlying:
        return "pga"
    base = t.name
    for sfx in ("_e", "_u", "_E", "_U"):
        if base.endswith(sfx):
            base = base[: -len(sfx)]
            break
    if base.endswith("2dp") or base.endswith("3dp"):
        return "pga"
    return "ega"


def emit_format_lambda(cls: str, *, param: str = "v",
                       cast_to_base: str | None = None) -> str:
    """Emit a `__format__` lambda that pipes Python f-string format specs into
    `fmt::format`. Empty spec uses the default format (matches `__str__`);
    non-empty spec is wrapped in `{:<spec>}` and dispatched through fmt's
    runtime parser. Bad specs raise `ValueError` (via `std::invalid_argument`,
    which nanobind translates to `PyExc_ValueError`) — matching Python's
    builtin convention for malformed format strings.

    The fmt grammar mirrors Python's PEP 3101 mini-language for the
    sign/width/precision/type cases that matter in practice (`f e g d x o b`,
    width, `.precision`, `+`/`-`/space, `<`/`>`/`^` align). Three Python-only
    features have no fmt equivalent: `,`/`_` thousands separators, the `%`
    percentage type, and full-string width (specs apply per-component for
    compound GA types). See `ga_py/README.md` for the user-facing details.

    `param` is the lambda parameter name (matches the surrounding emitter's
    convention — `v` for vector-shaped types, `s` for scalar-shaped types).

    `cast_to_base` is set when the bound C++ type does not have a
    `fmt::formatter` of its own and must be rendered through its base's
    formatter (the inherited-binding case).
    """
    target = (f"static_cast<const {cast_to_base}&>({param})"
              if cast_to_base else param)
    return (
        f'        .def("__format__",\n'
        f'            [](const {cls}& {param}, std::string_view spec) {{\n'
        f"                try {{\n"
        f'                    if (spec.empty()) return fmt::format("{{}}", {target});\n'
        f'                    return fmt::format(fmt::runtime("{{:" + std::string(spec) + "}}"),\n'
        f"                                       {target});\n"
        f"                }} catch (fmt::format_error const& e) {{\n"
        f"                    throw std::invalid_argument(e.what());\n"
        f"                }}\n"
        f'            }}, nb::arg("format_spec"))'
    )


def emit_array_protocol(cls: str, fields: list) -> tuple[str, str]:
    """Emit the numpy-interop pair (`__array__` + ndarray-ctor) for a vec- or
    inherited-shape type with public T fields.

    Tier 1 of §6.3 in ga_py/README.md: `np.array(v)` works without manual
    component unpacking, and `T(np.array([...]))` round-trips. Vectorised
    array-of-multivectors ops (Tier 2) remain deferred.

    Memory model: copy-out, copy-in.
      - `__array__` allocates a fresh `double[N]`, copies the field values
        in declaration order, and hands ownership to numpy via a capsule
        deleter. The C++ object's storage is never aliased, so this is
        safe regardless of struct layout / padding.
      - The ndarray ctor reads N doubles from a contiguous CPU buffer and
        placement-news a fresh instance via the type's existing N-double
        ctor (always present for vec-shaped types and for inherited types
        whose base inherits ctors via `using BaseT::BaseT;`).

    `fields` is the ordered list of public T fields used to lay out the
    ndarray. For vec-shape types, pass `t.fields`; for inherited-shape
    types (where `t.fields` is empty), pass the base type's fields.
    """
    n = len(fields)
    init_list = ", ".join(f"v.{f.name}" for f in fields)
    ctor_args = ", ".join(f"d[{i}]" for i in range(n))

    # NumPy 2.x calls `__array__(dtype=..., copy=...)`; we accept and ignore
    # both. Our buffer is always a fresh float64 copy — NumPy can cast it
    # downstream if a different dtype was requested.
    array_method = (
        f'        .def("__array__",\n'
        f'            []({cls} const& v, nb::handle /*dtype*/,\n'
        f"               nb::handle /*copy*/) {{\n"
        f"                auto* data = new double[{n}]{{{init_list}}};\n"
        f"                nb::capsule owner(data, [](void* p) noexcept {{\n"
        f"                    delete[] static_cast<double*>(p);\n"
        f"                }});\n"
        f"                return nb::ndarray<nb::numpy, double, nb::shape<{n}>>(\n"
        f"                    data, {{ {n} }}, owner);\n"
        f"            }},\n"
        f'            nb::arg("dtype").none() = nb::none(),\n'
        f'            nb::arg("copy").none() = nb::none())'
    )

    ndarray_ctor = (
        f'        .def("__init__",\n'
        f"            []({cls}* self,\n"
        f"               nb::ndarray<double, nb::shape<{n}>, nb::c_contig,\n"
        f"                           nb::device::cpu> arr) {{\n"
        f"                double const* d = arr.data();\n"
        f"                new (self) {cls}({ctor_args});\n"
        f"            }})"
    )

    return array_method, ndarray_ctor


def emit_inherited_binding(t: TypeAlias,
                           base_t: TypeAlias,
                           type_map: dict[str, str],
                           binary_ops: list[tuple[str, str, str, str, str]] | None = None
                           ) -> str:
    """Emit binding for a type whose fields/ops are inherited from a bound base
    (PGA primitives like `Point2d : public Vec2d<T>`).

    Strategy:
      - `nb::class_<derived, base>` declares Python inheritance.
      - Emit inherited base constructors explicitly (nanobind ctors are
        per-class, not inherited via `using`-directive).
      - Emit derived-specific (often mixed-type) constructors via the
        existing type_map lookup.
      - Provide a derived-named `__repr__` using inherited fields, so
        `repr(point2d(1,2))` shows `point2d(1, 2)` rather than `vec2d(1, 2)`.
      - Fields and operators come through inheritance — don't re-emit.
    """
    cls = t.name
    base = base_t.name

    # Inherited constructors (the base's all-T ctors are reachable on the
    # derived via `using BaseT::BaseT`, but nanobind needs an explicit
    # registration per class).
    ctor_lines: list[str] = []
    emitted_arities: set[int] = set()
    for c in base_t.constructors:
        if not c.param_types:
            ctor_lines.append("        .def(nb::init<>())")
            emitted_arities.add(0)
        elif all(normalize_param(p) == "T" for p in c.param_types):
            arity = len(c.param_types)
            if arity not in emitted_arities:
                emitted_arities.add(arity)
                args = ", ".join(["double"] * arity)
                ctor_lines.append(f"        .def(nb::init<{args}>())")

    # Derived-specific ctors: try to resolve params via type_map.
    emitted_mixed: set[tuple[str, ...]] = set()
    for c in t.constructors:
        if not c.param_types:
            continue  # default already covered above
        if all(normalize_param(p) == "T" for p in c.param_types):
            arity = len(c.param_types)
            if arity not in emitted_arities:
                emitted_arities.add(arity)
                args = ", ".join(["double"] * arity)
                ctor_lines.append(f"        .def(nb::init<{args}>())")
            continue
        resolved: list[str] = []
        ok = True
        for p in c.param_types:
            user = resolve_param_to_user_type(p, type_map)
            if user is None:
                ok = False
                break
            resolved.append(user)
        if not ok:
            continue
        sig_key = tuple(resolved)
        if sig_key in emitted_mixed:
            continue
        emitted_mixed.add(sig_key)
        ctor_lines.append(f"        .def(nb::init<{', '.join(resolved)}>())")

    # __repr__ named after the derived class, using inherited fields.
    if base_t.fields:
        repr_args = ", ".join("{}" for _ in base_t.fields)
        repr_field_refs = ", ".join(f"v.{f.name}" for f in base_t.fields)
        repr_lambda = (
            f'        .def("__repr__", [](const {cls}& v) {{\n'
            f'            return fmt::format("{cls}({repr_args})", {repr_field_refs});\n'
            f"        }})"
        )
    else:
        repr_lambda = (
            f'        .def("__repr__", [](const {cls}&) {{ return std::string("{cls}()"); }})'
        )
    str_lambda = (
        f'        .def("__str__", [](const {cls}& v) {{\n'
        f'            return fmt::format("{{}}", static_cast<const {base}&>(v));\n'
        f"        }})"
    )
    format_lambda = emit_format_lambda(cls, cast_to_base=base)

    binop_lines: list[str] = []
    for dunder, rhs, _ret, callable_text, kind in (binary_ops or []):
        binop_lines.append(render_op_def(cls, dunder, rhs, callable_text, kind))

    # Numpy interop: layout follows the *base type's* fields (derived has none
    # of its own — they're inherited via using-declarations). The ndarray ctor
    # works because base ctors are inherited via `using BaseT::BaseT;` in the
    # derived classes (see e.g. ga_type2dp.hpp line 186).
    array_lines: list[str] = []
    if base_t.fields:
        array_method, ndarray_ctor = emit_array_protocol(cls, base_t.fields)
        ctor_lines.append(ndarray_ctor)
        array_lines.append(array_method)

    body = "\n".join(ctor_lines + [repr_lambda, str_lambda, format_lambda]
                     + array_lines + binop_lines)
    return (
        f"void bind_{cls}(nb::module_& m) {{\n"
        f'    nb::class_<{cls}, {base}>(m, "{cls}")\n'
        f"{body}\n"
        f"        ;\n"
        f"}}\n"
    )


def emit_scalar_binding(t: TypeAlias,
                        binary_ops: list[tuple[str, str, str, str, str]] | None = None
                        ) -> str:
    """Emit nanobind binding for a Scalar_t<T, Tag>-shaped user type.

    Shape: private `value` field, `explicit operator T&()` accessor.
    Strategy:
      - Construct from a single double (maps to `Scalar_t(T const&)`).
      - Expose `.value` as a read/write property via the explicit conversion op.
      - Expose `__float__` so `float(s)` works — idiomatic Python for explicit
        numeric conversion, mirrors the C++ `explicit operator T const&()`.
      - Same-type arithmetic via ADL (`nb::self + nb::self`, etc.). Scalar *
        double / Scalar / double left off pending per-type verification.
    """
    cls = t.name

    ctor_lines = [
        "        .def(nb::init<>())",
        "        .def(nb::init<double>())",
    ]

    # Property `.value` — uses the explicit operator T& on the C++ side.
    value_prop = (
        '        .def_prop_rw("value",\n'
        f'            [](const {cls}& s) -> double {{ return static_cast<double>(s); }},\n'
        f'            [](      {cls}& s, double v) {{ static_cast<double&>(s) = v; }})'
    )

    float_method = (
        f'        .def("__float__", [](const {cls}& s) {{ return static_cast<double>(s); }})'
    )

    repr_lambda = (
        f'        .def("__repr__", [](const {cls}& s) {{\n'
        f'            return fmt::format("{cls}({{}})", static_cast<double>(s));\n'
        f"        }})"
    )
    str_lambda = (
        f'        .def("__str__", [](const {cls}& s) {{\n'
        f'            return fmt::format("{{}}", s);\n'
        f"        }})"
    )
    format_lambda = emit_format_lambda(cls, param="s")

    # Conservative operator set for Scalar_t<T, Tag>:
    #   - same-type + and - (defined for both scalar and pscalar)
    #   - Scalar_t * T and T * Scalar_t (defined via the `Scalar_t × U` overload)
    # Deliberately omitted:
    #   - Scalar_t * Scalar_t: defined for some types with differing return
    #     type (pscalar × pscalar collapses to scalar), so `nb::self * nb::self`
    #     fails to compile uniformly. Mixed-type operators are a later phase.
    op_lines = [
        "        .def(-nb::self)",
        "        .def(nb::self + nb::self)",
        "        .def(nb::self - nb::self)",
        "        .def(nb::self * double())",
        "        .def(double() * nb::self)",
        "        .def(nb::self / double())",
        # Scalar_t::operator== / <, <=, >, >= take any numeric U (member
        # template), not the same-tagged Scalar_t. Bind these explicitly via
        # the `explicit operator T const&()` accessor. Each comparison gets
        # two forms: scalar-vs-scalar (same tag) and scalar-vs-float —
        # mirroring the `(Scalar_t, Scalar_t) -> bool` and `(U) -> bool`
        # member overloads in C++. nb::is_operator() lets nanobind return
        # NotImplemented for unrelated types so dispatch stays clean.
        f'        .def("__eq__", []({cls} const& a, {cls} const& b) {{ '
        f'return static_cast<double>(a) == static_cast<double>(b); }}, '
        f'nb::is_operator())',
        f'        .def("__ne__", []({cls} const& a, {cls} const& b) {{ '
        f'return static_cast<double>(a) != static_cast<double>(b); }}, '
        f'nb::is_operator())',
        f'        .def("__lt__", []({cls} const& a, {cls} const& b) {{ '
        f'return static_cast<double>(a) < static_cast<double>(b); }}, '
        f'nb::is_operator())',
        f'        .def("__le__", []({cls} const& a, {cls} const& b) {{ '
        f'return static_cast<double>(a) <= static_cast<double>(b); }}, '
        f'nb::is_operator())',
        f'        .def("__gt__", []({cls} const& a, {cls} const& b) {{ '
        f'return static_cast<double>(a) > static_cast<double>(b); }}, '
        f'nb::is_operator())',
        f'        .def("__ge__", []({cls} const& a, {cls} const& b) {{ '
        f'return static_cast<double>(a) >= static_cast<double>(b); }}, '
        f'nb::is_operator())',
        # Comparisons with raw double on the right (member operator< form).
        f'        .def("__lt__", []({cls} const& a, double b) {{ '
        f'return static_cast<double>(a) < b; }}, nb::is_operator())',
        f'        .def("__le__", []({cls} const& a, double b) {{ '
        f'return static_cast<double>(a) <= b; }}, nb::is_operator())',
        f'        .def("__gt__", []({cls} const& a, double b) {{ '
        f'return static_cast<double>(a) > b; }}, nb::is_operator())',
        f'        .def("__ge__", []({cls} const& a, double b) {{ '
        f'return static_cast<double>(a) >= b; }}, nb::is_operator())',
    ]

    binop_lines: list[str] = []
    for dunder, rhs, _ret, callable_text, kind in (binary_ops or []):
        binop_lines.append(render_op_def(cls, dunder, rhs, callable_text, kind))

    body = "\n".join(
        ctor_lines
        + [value_prop, float_method, repr_lambda, str_lambda, format_lambda]
        + op_lines + binop_lines
    )
    return (
        f"void bind_{cls}(nb::module_& m) {{\n"
        f'    nb::class_<{cls}>(m, "{cls}")\n'
        f"{body}\n"
        f"        ;\n"
        f"}}\n"
    )


def emit_type_binding(t: TypeAlias,
                      type_map: dict[str, str] | None = None,
                      grade_methods: list[tuple[str, str]] | None = None,
                      binary_ops: list[tuple[str, str, str, str, str]] | None = None
                      ) -> str:
    """Emit nanobind class_<> registration for one user type with public T fields.

    `type_map` maps intermediate template names (e.g. `Vec3d`) to bound user
    types (e.g. `vec3d`); used to enable grade-composition (mixed-type)
    constructors. If None, only all-T ctors are emitted (back-compat).

    `grade_methods` is a list of (method_name, return_user_type) pairs
    (e.g. [('gr0','scalar3d'), …]) emitted as instance methods so that
    Python users can extract grade components: `m.gr0() -> scalar3d`.

    `binary_ops` is a list of (dunder, rhs_type, return_type, callable, kind)
    tuples emitted as `__add__`/`__mul__`/etc. lambdas — covers both same-
    and cross-type binary operators in one uniform pass.
    """
    cls = t.name  # e.g., "vec3d" — also the C++ typedef we bind against

    field_lines = [
        f'        .def_rw("{f.name}", &{cls}::{f.name})'
        for f in t.fields
    ]

    ctor_lines = []
    emitted_all_t_arities: set[int] = set()
    emitted_mixed_signatures: set[tuple[str, ...]] = set()
    for c in t.constructors:
        if not c.param_types:
            ctor_lines.append("        .def(nb::init<>())")
            continue
        if all(normalize_param(p) == "T" for p in c.param_types):
            # Emit only one all-T ctor per arity to avoid duplicate overloads
            # when the underlying has both `(T, T, T)` and `(T const&, T const&, T const&)`.
            arity = len(c.param_types)
            if arity not in emitted_all_t_arities:
                emitted_all_t_arities.add(arity)
                args = ", ".join(["double"] * arity)
                ctor_lines.append(f"        .def(nb::init<{args}>())")
            continue
        # Mixed-type ctor: try to resolve every param to a bound user type.
        if type_map is None:
            continue
        resolved: list[str] = []
        ok = True
        for p in c.param_types:
            user = resolve_param_to_user_type(p, type_map)
            if user is None:
                ok = False
                break
            resolved.append(user)
        if not ok:
            continue
        sig_key = tuple(resolved)
        if sig_key in emitted_mixed_signatures:
            continue
        emitted_mixed_signatures.add(sig_key)
        ctor_lines.append(f"        .def(nb::init<{', '.join(resolved)}>())")

    # Hand-curated converting constructors (see CONVERTING_CTORS docstring).
    for sig in CONVERTING_CTORS.get(t.name, []):
        # First arg is taken by const& reference; remaining args by value.
        # All current conversions match this shape; widen this if other
        # patterns ever appear.
        first, *rest = sig
        init_args = [f"{first} const&", *rest]
        ctor_lines.append(f"        .def(nb::init<{', '.join(init_args)}>())")

    repr_args = ", ".join("{}" for _ in t.fields)
    repr_field_refs = ", ".join(f"v.{f.name}" for f in t.fields)
    repr_lambda = (
        f'        .def("__repr__", [](const {cls}& v) {{\n'
        f'            return fmt::format("{cls}({repr_args})", {repr_field_refs});\n'
        f"        }})"
    )
    str_lambda = (
        f'        .def("__str__", [](const {cls}& v) {{\n'
        f'            return fmt::format("{{}}", v);\n'
        f"        }})"
    )
    format_lambda = emit_format_lambda(cls)

    # Operators kept on `nb::self`:
    #   - unary minus
    #   - same-type +, -  (templated on Vec_t<T,Tag>; manifest only knows
    #     them at the bare-template level, so type_map resolution misses
    #     them — must keep nb::self to cover them)
    #   - in-place +=, -=, *=, /=
    #   - same-type ==, !=
    #   - scalar mul/div by double
    op_lines = [
        "        .def(-nb::self)",
        "        .def(nb::self + nb::self)",
        "        .def(nb::self - nb::self)",
        "        .def(nb::self += nb::self)",
        "        .def(nb::self -= nb::self)",
        "        .def(nb::self == nb::self)",
        "        .def(nb::self != nb::self)",
        "        .def(nb::self * double())",
        "        .def(double() * nb::self)",
        "        .def(nb::self / double())",
        "        .def(nb::self *= double())",
        "        .def(nb::self /= double())",
    ]

    # Binary operators (cross- and same-type) emitted as lambdas from the
    # manifest. Covers `a + b`, `a - b`, `a * b`, `a << b`, `a >> b`, and
    # `a ^ b` (mapped to wdg). Same-type +, - already covered by nb::self
    # above (templated overloads at the Vec_t level), so skip those here.
    SAME_TYPE_DUNDERS_VIA_NB_SELF = {"__add__", "__sub__"}
    binop_lines: list[str] = []
    for dunder, rhs, _ret, callable_text, kind in (binary_ops or []):
        if rhs == cls and dunder in SAME_TYPE_DUNDERS_VIA_NB_SELF:
            continue
        binop_lines.append(render_op_def(cls, dunder, rhs, callable_text, kind))

    # Grade-extraction methods. C++ free function `gr0(M)` becomes Python
    # `m.gr0()`. Lambda dispatches via ADL to the templated free function.
    grade_lines: list[str] = []
    for method_name, _return_type in (grade_methods or []):
        grade_lines.append(
            f'        .def("{method_name}", [](const {cls}& M) {{ return {method_name}(M); }})'
        )

    array_lines: list[str] = []
    if t.fields:
        array_method, ndarray_ctor = emit_array_protocol(cls, t.fields)
        ctor_lines.append(ndarray_ctor)
        array_lines.append(array_method)

    body = "\n".join(ctor_lines + field_lines
                     + [repr_lambda, str_lambda, format_lambda]
                     + array_lines + op_lines + binop_lines + grade_lines)
    return (
        f"void bind_{cls}(nb::module_& m) {{\n"
        f'    nb::class_<{cls}>(m, "{cls}")\n'
        f"{body}\n"
        f"        ;\n"
        f"}}\n"
    )


def emit_register_all(type_to_sub: dict[str, str],
                      types_by_name: dict[str, TypeAlias],
                      type_map: dict[str, str]) -> str:
    """Emit the dispatcher that the hand-written module.cpp calls.

    Order matters: nanobind requires base classes to be registered before
    derived classes. We do a stable topological sort: types with no bound
    base first, then derived types after their bases.
    """
    # Resolve each type's bound base (if any) for topological ordering.
    base_of: dict[str, str | None] = {}
    for name in type_to_sub:
        t = types_by_name.get(name)
        if t and t.base_class:
            base_user = type_map.get(t.base_class)
            base_of[name] = base_user if base_user in type_to_sub else None
        else:
            base_of[name] = None

    # Kahn-style ordering: emit names whose base is already emitted (or None).
    remaining = set(type_to_sub)
    ordered: list[str] = []
    while remaining:
        ready = sorted(n for n in remaining
                       if base_of[n] is None or base_of[n] in ordered)
        if not ready:
            # Cycle or unresolved — fall back to alphabetical for the rest.
            ordered.extend(sorted(remaining))
            break
        ordered.extend(ready)
        remaining.difference_update(ready)

    forward_decls = "\n".join(f"void bind_{n}(nb::module_& m);" for n in sorted(type_to_sub))
    calls = "\n".join(f"    bind_{n}({type_to_sub[n]});" for n in ordered)
    return (
        "// AUTO-GENERATED BY ga_bindgen — DO NOT EDIT.\n"
        "// Regenerate via: python3 ga_bindgen/src/emit_nanobind.py --all\n"
        "\n"
        "#include <nanobind/nanobind.h>\n"
        "\n"
        "namespace nb = nanobind;\n"
        "\n"
        f"{forward_decls}\n"
        "\n"
        "void register_functions_ega(nb::module_& m);\n"
        "void register_functions_pga(nb::module_& m);\n"
        "void register_functions_top(nb::module_& m);\n"
        "void register_constants_ega(nb::module_& m);\n"
        "void register_constants_pga(nb::module_& m);\n"
        "void register_constants_top(nb::module_& m);\n"
        "\n"
        "void register_all(nb::module_& top, nb::module_& ega, nb::module_& pga) {\n"
        f"{calls}\n"
        "    register_functions_ega(ega);\n"
        "    register_functions_pga(pga);\n"
        "    register_functions_top(top);\n"
        "    register_constants_ega(ega);\n"
        "    register_constants_pga(pga);\n"
        "    register_constants_top(top);\n"
        "}\n"
    )


def emit_cmake_list(names: list[str], out_dir: Path) -> str:
    """Emit a .cmake file listing generated sources, for CMake to include()."""
    lines = ["# AUTO-GENERATED BY ga_bindgen — DO NOT EDIT.",
             "# Regenerate via: python3 ga_bindgen/src/emit_nanobind.py --all",
             "",
             "set(GA_PY_GENERATED_SOURCES"]
    for n in sorted(names):
        lines.append(f"    ${{CMAKE_CURRENT_SOURCE_DIR}}/src/generated/bindings_{n}.cpp")
    lines.append(f"    ${{CMAKE_CURRENT_SOURCE_DIR}}/src/generated/register_all.cpp")
    for submod in ("ega", "pga", "top"):
        lines.append(f"    ${{CMAKE_CURRENT_SOURCE_DIR}}/src/generated/bindings_functions_{submod}.cpp")
    for submod in ("ega", "pga", "top"):
        lines.append(f"    ${{CMAKE_CURRENT_SOURCE_DIR}}/src/generated/bindings_constants_{submod}.cpp")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--type",
                      help="Emit a single type (quick iteration during "
                           "binding development). Without this flag the "
                           "default is full regeneration.")
    mode.add_argument("--all", action="store_true",
                      help="Emit every eligible type + register_all.cpp + "
                           "bindings_list.cmake. This is the default; the "
                           "flag is accepted for backward compatibility.")
    ap.add_argument("--functions-from", default="",
                    help="Comma-separated source-file basenames; restrict "
                         "free-function emission to overloads declared in "
                         "those files. Empty (default) means emit every "
                         "bindable free function. Provided as an escape "
                         "hatch for incremental enablement during binding "
                         "development.")
    args = ap.parse_args()

    manifest = Manifest.from_json(Path(args.manifest).read_text())
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Default mode: full regeneration. `--all` is a no-op alias kept for
    # backward compatibility; explicit `--type X` selects single-type mode.
    if not args.type:
        # Wipe any stale generated files so removed types don't linger.
        for old in out_dir.glob("bindings_*.cpp"):
            old.unlink()

        # Collect eligible user typedefs (those declared in target namespaces).
        # Also restrict to typedefs in `hd::ga` (where user types live).
        eligible = [t for t in manifest.types
                    if t.namespace == "hd::ga" and is_eligible(t)]

        # Build the template-name → user-type map ONCE from ALL eligible
        # types, so e.g. mvec3d's ctor `MVec8_t(Scalar3d<T>, Vec3d<T>, ...)`
        # resolves through the entries for scalar3d and vec3d.
        type_map = build_type_name_map(eligible)
        grade_methods_per_type = collect_grade_extractors(manifest, type_map)
        binary_ops_per_type = collect_binary_operators(manifest, type_map)
        types_by_name: dict[str, TypeAlias] = {t.name: t for t in eligible}

        type_to_sub: dict[str, str] = {}
        for t in eligible:
            ops = binary_ops_per_type.get(t.name)
            if is_scalar_shape(t):
                body = emit_scalar_binding(t, ops)
            elif is_inherited_shape(t):
                base_user = type_map.get(t.base_class) if t.base_class else None
                base_t = types_by_name.get(base_user) if base_user else None
                if base_t is None:
                    # Base class isn't bound — skip (would fail to compile).
                    continue
                body = emit_inherited_binding(t, base_t, type_map, ops)
            else:
                body = emit_type_binding(t, type_map,
                                         grade_methods_per_type.get(t.name),
                                         ops)
            (out_dir / f"bindings_{t.name}.cpp").write_text(
                GENERATED_HEADER + "\n" + body
            )
            type_to_sub[t.name] = submodule_for(t)

        # Free function emission: with --all and no --functions-from, emit
        # every bindable free function (the obvious meaning of "all"). With
        # --functions-from, restrict to overloads declared in those files
        # (kept for incremental enablement during binding development).
        file_filter: set[str] | None = None
        if args.functions_from:
            file_filter = {x.strip() for x in args.functions_from.split(",") if x.strip()}

        free_fns = collect_free_functions(manifest, type_map, file_filter)
        for submod in ("ega", "pga", "top"):
            (out_dir / f"bindings_functions_{submod}.cpp").write_text(
                GENERATED_HEADER + "\n" + emit_function_module(submod, free_fns.get(submod, {}))
            )

        constants = collect_constants(manifest, type_map)
        for submod in ("ega", "pga", "top"):
            (out_dir / f"bindings_constants_{submod}.cpp").write_text(
                GENERATED_HEADER + "\n" + emit_constants_module(submod, constants.get(submod, []))
            )

        (out_dir / "register_all.cpp").write_text(
            emit_register_all(type_to_sub, types_by_name, type_map)
        )
        (GA_PY / "src" / "generated" / "bindings_list.cmake").write_text(
            emit_cmake_list(list(type_to_sub), out_dir)
        )

        # Print free-function summary
        n_total = sum(len(ovs) for sm in free_fns.values() for ovs in sm.values())
        filter_desc = (f"{len(file_filter)} source files (--functions-from)"
                       if file_filter is not None
                       else "all source files")
        print(f"\nFree-function emission ({n_total} overloads from {filter_desc}):")
        for submod in ("ega", "pga", "top"):
            fns = free_fns.get(submod, {})
            n_ovs = sum(len(ovs) for ovs in fns.values())
            print(f"  {submod}: {len(fns)} unique fn names, {n_ovs} overloads")

        print(f"Emitted {len(eligible)} type bindings to {out_dir}:")
        ega = sorted(n for n, s in type_to_sub.items() if s == "ega")
        pga = sorted(n for n, s in type_to_sub.items() if s == "pga")
        print(f"  ega ({len(ega)}): {', '.join(ega)}")
        print(f"  pga ({len(pga)}): {', '.join(pga)}")
        print(f"\n  skipped {len(manifest.types) - len(eligible)} ineligible types")
        print(f"  (internal _t templates and uppercase template aliases still")
        print(f"   parameterized on T)")
        return 0

    # Single-type mode: emit only `--type X` for quick iteration.
    type_name = args.type
    target = next((t for t in manifest.types if t.name == type_name), None)
    if target is None:
        print(f"Type '{type_name}' not found in manifest.", file=sys.stderr)
        return 1
    if not is_eligible(target):
        print(f"Type '{type_name}' is not currently emittable (private fields or "
              "non-T field types).", file=sys.stderr)
        return 1
    if is_scalar_shape(target):
        body = emit_scalar_binding(target)
    else:
        type_map = build_type_name_map([t for t in manifest.types if t.namespace == "hd::ga"])
        body = emit_type_binding(target, type_map)
    (out_dir / f"bindings_{target.name}.cpp").write_text(
        GENERATED_HEADER + "\n" + body
    )
    print(f"Generated: {out_dir / f'bindings_{target.name}.cpp'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
