"""
Python bindings for the hd::ga geometric algebra library.
Generated from C++ headers by ga_bindgen.
"""

from collections.abc import Sequence
import enum
from typing import overload

from . import ega as ega, pga as pga, sta as sta


class geo_angle(enum.Enum):
    latitude = 0

    longitude = 1

def Hz2radps(arg: float, /) -> float: ...

def deg2rad(arg: float, /) -> float: ...

@overload
def gr(arg: ega.scalar2d, /) -> int: ...

@overload
def gr(arg: ega.vec2d, /) -> int: ...

@overload
def gr(arg: ega.pscalar2d, /) -> int: ...

@overload
def gr(arg: ega.scalar3d, /) -> int: ...

@overload
def gr(arg: ega.vec3d, /) -> int: ...

@overload
def gr(arg: ega.bivec3d, /) -> int: ...

@overload
def gr(arg: ega.pscalar3d, /) -> int: ...

@overload
def gr(arg: pga.scalar2dp, /) -> int: ...

@overload
def gr(arg: pga.vec2dp, /) -> int: ...

@overload
def gr(arg: pga.bivec2dp, /) -> int: ...

@overload
def gr(arg: pga.pscalar2dp, /) -> int: ...

@overload
def gr(arg: pga.scalar3dp, /) -> int: ...

@overload
def gr(arg: pga.vec3dp, /) -> int: ...

@overload
def gr(arg: pga.bivec3dp, /) -> int: ...

@overload
def gr(arg: pga.trivec3dp, /) -> int: ...

@overload
def gr(arg: pga.pscalar3dp, /) -> int: ...

@overload
def gr(arg: sta.scalar4ds, /) -> int: ...

@overload
def gr(arg: sta.vec4ds, /) -> int: ...

@overload
def gr(arg: sta.bivec4ds, /) -> int: ...

@overload
def gr(arg: sta.trivec4ds, /) -> int: ...

@overload
def gr(arg: sta.pscalar4ds, /) -> int: ...

@overload
def gr(arg: ega.scalar2dc, /) -> int: ...

@overload
def gr(arg: ega.vec2dc, /) -> int: ...

@overload
def gr(arg: ega.bivec2dc, /) -> int: ...

@overload
def gr(arg: ega.trivec2dc, /) -> int: ...

@overload
def gr(arg: ega.pscalar2dc, /) -> int: ...

@overload
def gr(arg: ega.scalar3dc, /) -> int: ...

@overload
def gr(arg: ega.vec3dc, /) -> int: ...

@overload
def gr(arg: ega.bivec3dc, /) -> int: ...

@overload
def gr(arg: ega.trivec3dc, /) -> int: ...

@overload
def gr(arg: ega.quadvec3dc, /) -> int: ...

@overload
def gr(arg: ega.pscalar3dc, /) -> int: ...

def linear_step(arg0: float, arg1: float, arg2: float, /) -> float: ...

def lstsq_solve(arg0: Sequence[float], arg1: Sequence[float], arg2: int, /) -> list[float]: ...

def lu_solve(arg0: Sequence[float], arg1: Sequence[float], arg2: int, /) -> list[float]: ...

def rad2deg(arg: float, /) -> float: ...

def radps2Hz(arg: float, /) -> float: ...

def radps2rpm(arg: float, /) -> float: ...

@overload
def rgr(arg: pga.scalar2dp, /) -> int: ...

@overload
def rgr(arg: pga.vec2dp, /) -> int: ...

@overload
def rgr(arg: pga.bivec2dp, /) -> int: ...

@overload
def rgr(arg: pga.pscalar2dp, /) -> int: ...

@overload
def rgr(arg: pga.scalar3dp, /) -> int: ...

@overload
def rgr(arg: pga.vec3dp, /) -> int: ...

@overload
def rgr(arg: pga.bivec3dp, /) -> int: ...

@overload
def rgr(arg: pga.trivec3dp, /) -> int: ...

@overload
def rgr(arg: pga.pscalar3dp, /) -> int: ...

@overload
def rgr(arg: sta.scalar4ds, /) -> int: ...

@overload
def rgr(arg: sta.vec4ds, /) -> int: ...

@overload
def rgr(arg: sta.bivec4ds, /) -> int: ...

@overload
def rgr(arg: sta.trivec4ds, /) -> int: ...

@overload
def rgr(arg: sta.pscalar4ds, /) -> int: ...

@overload
def rgr(arg: ega.scalar2dc, /) -> int: ...

@overload
def rgr(arg: ega.vec2dc, /) -> int: ...

@overload
def rgr(arg: ega.bivec2dc, /) -> int: ...

@overload
def rgr(arg: ega.trivec2dc, /) -> int: ...

@overload
def rgr(arg: ega.pscalar2dc, /) -> int: ...

@overload
def rgr(arg: ega.scalar3dc, /) -> int: ...

@overload
def rgr(arg: ega.vec3dc, /) -> int: ...

@overload
def rgr(arg: ega.bivec3dc, /) -> int: ...

@overload
def rgr(arg: ega.trivec3dc, /) -> int: ...

@overload
def rgr(arg: ega.quadvec3dc, /) -> int: ...

@overload
def rgr(arg: ega.pscalar3dc, /) -> int: ...

def rk4_get_time(arg0: float, arg1: float, arg2: int, /) -> float: ...

def rpm2radps(arg: float, /) -> float: ...

def sign(arg: float, /) -> float: ...

def smooth_step(arg0: float, arg1: float, arg2: float, /) -> float: ...

def smoother_step(arg0: float, arg1: float, arg2: float, /) -> float: ...

@overload
def to_geo_pos(arg0: "hd::ga::geo_pos_dms", arg1: float, /) -> ega.geo_pos: ...

@overload
def to_geo_pos(arg0: "hd::ga::geo_pos_dms2dp", arg1: float, /) -> pga.geo_pos2dp: ...

@overload
def rk4_step(u: Sequence[ega.vec2d], uh: Sequence[Sequence[ega.vec2d]], rhs: Sequence[ega.vec2d], dt: float, rk_step: int) -> tuple[list[ega.vec2d], list[list[ega.vec2d]]]: ...

@overload
def rk4_step(u: Sequence[ega.vec3d], uh: Sequence[Sequence[ega.vec3d]], rhs: Sequence[ega.vec3d], dt: float, rk_step: int) -> tuple[list[ega.vec3d], list[list[ega.vec3d]]]: ...

@overload
def rk4_step(u: Sequence[pga.vec2dp], uh: Sequence[Sequence[pga.vec2dp]], rhs: Sequence[pga.vec2dp], dt: float, rk_step: int) -> tuple[list[pga.vec2dp], list[list[pga.vec2dp]]]: ...

@overload
def rk4_step(u: Sequence[pga.vec3dp], uh: Sequence[Sequence[pga.vec3dp]], rhs: Sequence[pga.vec3dp], dt: float, rk_step: int) -> tuple[list[pga.vec3dp], list[list[pga.vec3dp]]]:
    """
    Runge-Kutta 4 sub-step (vector overload). Returns (u_new, (uh0_new, uh1_new)). VecType is dispatched on the element type of `u`.
    """
