"""
Python bindings for the hd::ga geometric algebra library.
Generated from C++ headers by ga_bindgen.
"""

from collections.abc import Sequence
from typing import overload

from . import ega as ega, pga as pga


def Hz2radps(arg: float, /) -> float: ...

def deg2rad(arg: float, /) -> float: ...

@overload
def gr(arg: ega.scalar2d, /) -> int: ...

@overload
def gr(arg: ega.vec2d, /) -> int: ...

@overload
def gr(arg: ega.pscalar2d, /) -> int: ...

@overload
def gr(arg: ega.scalar3d, /) -> int: ...

@overload
def gr(arg: ega.vec3d, /) -> int: ...

@overload
def gr(arg: ega.bivec3d, /) -> int: ...

@overload
def gr(arg: ega.pscalar3d, /) -> int: ...

@overload
def gr(arg: pga.scalar2dp, /) -> int: ...

@overload
def gr(arg: pga.vec2dp, /) -> int: ...

@overload
def gr(arg: pga.bivec2dp, /) -> int: ...

@overload
def gr(arg: pga.pscalar2dp, /) -> int: ...

@overload
def gr(arg: pga.scalar3dp, /) -> int: ...

@overload
def gr(arg: pga.vec3dp, /) -> int: ...

@overload
def gr(arg: pga.bivec3dp, /) -> int: ...

@overload
def gr(arg: pga.trivec3dp, /) -> int: ...

@overload
def gr(arg: pga.pscalar3dp, /) -> int: ...

@overload
def gr(arg: ega.scalar4d, /) -> int: ...

@overload
def gr(arg: ega.vec4d, /) -> int: ...

@overload
def gr(arg: ega.bivec4d, /) -> int: ...

@overload
def gr(arg: ega.trivec4d, /) -> int: ...

@overload
def gr(arg: ega.pscalar4d, /) -> int: ...

def rad2deg(arg: float, /) -> float: ...

def radps2Hz(arg: float, /) -> float: ...

def radps2rpm(arg: float, /) -> float: ...

@overload
def rgr(arg: pga.scalar2dp, /) -> int: ...

@overload
def rgr(arg: pga.vec2dp, /) -> int: ...

@overload
def rgr(arg: pga.bivec2dp, /) -> int: ...

@overload
def rgr(arg: pga.pscalar2dp, /) -> int: ...

@overload
def rgr(arg: pga.scalar3dp, /) -> int: ...

@overload
def rgr(arg: pga.vec3dp, /) -> int: ...

@overload
def rgr(arg: pga.bivec3dp, /) -> int: ...

@overload
def rgr(arg: pga.trivec3dp, /) -> int: ...

@overload
def rgr(arg: pga.pscalar3dp, /) -> int: ...

def rk4_get_time(arg0: float, arg1: float, arg2: int, /) -> float: ...

def rpm2radps(arg: float, /) -> float: ...

def sign(arg: float, /) -> float: ...

@overload
def rk4_step(u: Sequence[ega.vec2d], uh: Sequence[Sequence[ega.vec2d]], rhs: Sequence[ega.vec2d], dt: float, rk_step: int) -> tuple[list[ega.vec2d], list[list[ega.vec2d]]]:
    """
    Runge-Kutta 4 sub-step (vector overload). Returns (u_new, (uh0_new, uh1_new)). VecType is dispatched on the element type of `u`.
    """

@overload
def rk4_step(u: Sequence[ega.vec3d], uh: Sequence[Sequence[ega.vec3d]], rhs: Sequence[ega.vec3d], dt: float, rk_step: int) -> tuple[list[ega.vec3d], list[list[ega.vec3d]]]: ...

@overload
def rk4_step(u: Sequence[pga.vec2dp], uh: Sequence[Sequence[pga.vec2dp]], rhs: Sequence[pga.vec2dp], dt: float, rk_step: int) -> tuple[list[pga.vec2dp], list[list[pga.vec2dp]]]: ...

@overload
def rk4_step(u: Sequence[pga.vec3dp], uh: Sequence[Sequence[pga.vec3dp]], rhs: Sequence[pga.vec3dp], dt: float, rk_step: int) -> tuple[list[pga.vec3dp], list[list[pga.vec3dp]]]: ...
