"""Euclidean geometric algebra (2D, 3D, 4D)"""

from collections.abc import Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


class bivec3d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C', device='cpu')], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def z(self) -> float: ...

    @z.setter
    def z(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(3))]: ...

    def __neg__(self) -> bivec3d: ...

    @overload
    def __add__(self, arg: bivec3d, /) -> bivec3d: ...

    @overload
    def __add__(self, arg: scalar3d, /) -> mvec3d_e: ...

    @overload
    def __add__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __add__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: pscalar3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: bivec3d, /) -> bivec3d: ...

    @overload
    def __sub__(self, arg: scalar3d, /) -> mvec3d_e: ...

    @overload
    def __sub__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __sub__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: pscalar3d, /) -> mvec3d: ...

    def __iadd__(self, arg: bivec3d, /) -> bivec3d: ...

    def __isub__(self, arg: bivec3d, /) -> bivec3d: ...

    def __eq__(self, arg: bivec3d, /) -> bool: ...

    def __ne__(self, arg: bivec3d, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> bivec3d: ...

    @overload
    def __mul__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: pscalar3d, /) -> vec3d: ...

    @overload
    def __mul__(self, arg: bivec3d, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: vec3d, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: scalar3d, /) -> bivec3d: ...

    def __rmul__(self, arg: float, /) -> bivec3d: ...

    def __truediv__(self, arg: float, /) -> bivec3d: ...

    def __imul__(self, arg: float, /) -> bivec3d: ...

    def __itruediv__(self, arg: float, /) -> bivec3d: ...

    @overload
    def __lshift__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __lshift__(self, arg: pscalar3d, /) -> vec3d: ...

    @overload
    def __lshift__(self, arg: bivec3d, /) -> scalar3d: ...

    @overload
    def __lshift__(self, arg: vec3d, /) -> scalar3d: ...

    @overload
    def __lshift__(self, arg: scalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: bivec3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: vec3d, /) -> vec3d: ...

    @overload
    def __rshift__(self, arg: scalar3d, /) -> bivec3d: ...

    @overload
    def __xor__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __xor__(self, arg: bivec3d, /) -> scalar3d: ...

    @overload
    def __xor__(self, arg: vec3d, /) -> pscalar3d: ...

    @overload
    def __xor__(self, arg: scalar3d, /) -> bivec3d: ...

class bivec4d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C', device='cpu')], /) -> None: ...

    @property
    def vx(self) -> float: ...

    @vx.setter
    def vx(self, arg: float, /) -> None: ...

    @property
    def vy(self) -> float: ...

    @vy.setter
    def vy(self, arg: float, /) -> None: ...

    @property
    def vz(self) -> float: ...

    @vz.setter
    def vz(self, arg: float, /) -> None: ...

    @property
    def mx(self) -> float: ...

    @mx.setter
    def mx(self, arg: float, /) -> None: ...

    @property
    def my(self) -> float: ...

    @my.setter
    def my(self, arg: float, /) -> None: ...

    @property
    def mz(self) -> float: ...

    @mz.setter
    def mz(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(6))]: ...

    def __neg__(self) -> bivec4d: ...

    @overload
    def __add__(self, arg: bivec4d, /) -> bivec4d: ...

    @overload
    def __add__(self, arg: scalar4d, /) -> mvec4d_e: ...

    @overload
    def __sub__(self, arg: bivec4d, /) -> bivec4d: ...

    @overload
    def __sub__(self, arg: scalar4d, /) -> mvec4d_e: ...

    def __iadd__(self, arg: bivec4d, /) -> bivec4d: ...

    def __isub__(self, arg: bivec4d, /) -> bivec4d: ...

    def __eq__(self, arg: bivec4d, /) -> bool: ...

    def __ne__(self, arg: bivec4d, /) -> bool: ...

    def __mul__(self, arg: float, /) -> bivec4d: ...

    def __rmul__(self, arg: float, /) -> bivec4d: ...

    def __truediv__(self, arg: float, /) -> bivec4d: ...

    def __imul__(self, arg: float, /) -> bivec4d: ...

    def __itruediv__(self, arg: float, /) -> bivec4d: ...

class mvec2d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar2d, /) -> None: ...

    @overload
    def __init__(self, arg: vec2d, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar2d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar2d, arg1: pscalar2d, /) -> None: ...

    @overload
    def __init__(self, arg: mvec2d_e, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar2d, arg1: vec2d, arg2: pscalar2d, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(4))]: ...

    def __neg__(self) -> mvec2d: ...

    @overload
    def __add__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __add__(self, arg: scalar2d, /) -> mvec2d: ...

    @overload
    def __add__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __add__(self, arg: pscalar2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: scalar2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: pscalar2d, /) -> mvec2d: ...

    def __iadd__(self, arg: mvec2d, /) -> mvec2d: ...

    def __isub__(self, arg: mvec2d, /) -> mvec2d: ...

    def __eq__(self, arg: mvec2d, /) -> bool: ...

    def __ne__(self, arg: mvec2d, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: mvec2d_e, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: pscalar2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: scalar2d, /) -> mvec2d: ...

    def __rmul__(self, arg: float, /) -> mvec2d: ...

    def __truediv__(self, arg: float, /) -> mvec2d: ...

    def __imul__(self, arg: float, /) -> mvec2d: ...

    def __itruediv__(self, arg: float, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: mvec2d_e, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: pscalar2d, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __rshift__(self, arg: mvec2d_e, /) -> mvec2d: ...

    @overload
    def __rshift__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __rshift__(self, arg: scalar2d, /) -> mvec2d: ...

    @overload
    def __xor__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __xor__(self, arg: mvec2d_e, /) -> mvec2d: ...

    @overload
    def __xor__(self, arg: pscalar2d, /) -> pscalar2d: ...

    @overload
    def __xor__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __xor__(self, arg: scalar2d, /) -> mvec2d: ...

    def gr0(self) -> scalar2d: ...

    def gr1(self) -> vec2d: ...

    def gr2(self) -> pscalar2d: ...

class mvec2d_e:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar2d, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar2d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar2d, arg1: pscalar2d, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(2), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(2))]: ...

    def __neg__(self) -> mvec2d_e: ...

    @overload
    def __add__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __add__(self, arg: scalar2d, /) -> mvec2d_e: ...

    @overload
    def __add__(self, arg: pscalar2d, /) -> mvec2d_e: ...

    @overload
    def __sub__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __sub__(self, arg: scalar2d, /) -> mvec2d_e: ...

    @overload
    def __sub__(self, arg: pscalar2d, /) -> mvec2d_e: ...

    def __iadd__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    def __isub__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    def __eq__(self, arg: mvec2d_e, /) -> bool: ...

    def __ne__(self, arg: mvec2d_e, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec2d_e: ...

    @overload
    def __mul__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __mul__(self, arg: pscalar2d, /) -> mvec2d_e: ...

    @overload
    def __mul__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __mul__(self, arg: scalar2d, /) -> mvec2d_e: ...

    def __rmul__(self, arg: float, /) -> mvec2d_e: ...

    def __truediv__(self, arg: float, /) -> mvec2d_e: ...

    def __imul__(self, arg: float, /) -> mvec2d_e: ...

    def __itruediv__(self, arg: float, /) -> mvec2d_e: ...

    @overload
    def __lshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __lshift__(self, arg: pscalar2d, /) -> mvec2d_e: ...

    @overload
    def __lshift__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __lshift__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __rshift__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __rshift__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __rshift__(self, arg: scalar2d, /) -> mvec2d_e: ...

    @overload
    def __xor__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __xor__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __xor__(self, arg: pscalar2d, /) -> pscalar2d: ...

    @overload
    def __xor__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __xor__(self, arg: scalar2d, /) -> mvec2d_e: ...

    def gr0(self) -> scalar2d: ...

    def gr2(self) -> pscalar2d: ...

class mvec3d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar3d, /) -> None: ...

    @overload
    def __init__(self, arg: vec3d, /) -> None: ...

    @overload
    def __init__(self, arg: bivec3d, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar3d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar3d, arg1: pscalar3d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar3d, arg1: bivec3d, /) -> None: ...

    @overload
    def __init__(self, arg: mvec3d_e, /) -> None: ...

    @overload
    def __init__(self, arg0: vec3d, arg1: pscalar3d, /) -> None: ...

    @overload
    def __init__(self, arg: mvec3d_u, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar3d, arg1: vec3d, arg2: bivec3d, arg3: pscalar3d, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(8), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    @property
    def c4(self) -> float: ...

    @c4.setter
    def c4(self, arg: float, /) -> None: ...

    @property
    def c5(self) -> float: ...

    @c5.setter
    def c5(self, arg: float, /) -> None: ...

    @property
    def c6(self) -> float: ...

    @c6.setter
    def c6(self, arg: float, /) -> None: ...

    @property
    def c7(self) -> float: ...

    @c7.setter
    def c7(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(8))]: ...

    def __neg__(self) -> mvec3d: ...

    @overload
    def __add__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: scalar3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: pscalar3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: scalar3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: pscalar3d, /) -> mvec3d: ...

    def __iadd__(self, arg: mvec3d, /) -> mvec3d: ...

    def __isub__(self, arg: mvec3d, /) -> mvec3d: ...

    def __eq__(self, arg: mvec3d, /) -> bool: ...

    def __ne__(self, arg: mvec3d, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_e, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_u, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: pscalar3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: scalar3d, /) -> mvec3d: ...

    def __rmul__(self, arg: float, /) -> mvec3d: ...

    def __truediv__(self, arg: float, /) -> mvec3d: ...

    def __imul__(self, arg: float, /) -> mvec3d: ...

    def __itruediv__(self, arg: float, /) -> mvec3d: ...

    def __lshift__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __rshift__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __rshift__(self, arg: pscalar3d, /) -> mvec3d: ...

    @overload
    def __rshift__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __rshift__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __rshift__(self, arg: scalar3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: pscalar3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: scalar3d, /) -> mvec3d: ...

    def gr0(self) -> scalar3d: ...

    def gr1(self) -> vec3d: ...

    def gr2(self) -> bivec3d: ...

    def gr3(self) -> pscalar3d: ...

class mvec3d_e:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar3d, /) -> None: ...

    @overload
    def __init__(self, arg: bivec3d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar3d, arg1: bivec3d, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(4))]: ...

    def __neg__(self) -> mvec3d_e: ...

    @overload
    def __add__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __add__(self, arg: scalar3d, /) -> mvec3d_e: ...

    @overload
    def __add__(self, arg: bivec3d, /) -> mvec3d_e: ...

    @overload
    def __sub__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __sub__(self, arg: scalar3d, /) -> mvec3d_e: ...

    @overload
    def __sub__(self, arg: bivec3d, /) -> mvec3d_e: ...

    def __iadd__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    def __isub__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    def __eq__(self, arg: mvec3d_e, /) -> bool: ...

    def __ne__(self, arg: mvec3d_e, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: pscalar3d, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: bivec3d, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: vec3d, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: scalar3d, /) -> mvec3d_e: ...

    def __rmul__(self, arg: float, /) -> mvec3d_e: ...

    def __truediv__(self, arg: float, /) -> mvec3d_e: ...

    def __imul__(self, arg: float, /) -> mvec3d_e: ...

    def __itruediv__(self, arg: float, /) -> mvec3d_e: ...

    def __rshift__(self, arg: scalar3d, /) -> mvec3d_e: ...

    def gr0(self) -> scalar3d: ...

    def gr2(self) -> bivec3d: ...

class mvec3d_u:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, arg: vec3d, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar3d, /) -> None: ...

    @overload
    def __init__(self, arg0: vec3d, arg1: pscalar3d, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(4))]: ...

    def __neg__(self) -> mvec3d_u: ...

    @overload
    def __add__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __add__(self, arg: pscalar3d, /) -> mvec3d_u: ...

    @overload
    def __add__(self, arg: vec3d, /) -> mvec3d_u: ...

    @overload
    def __sub__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __sub__(self, arg: pscalar3d, /) -> mvec3d_u: ...

    @overload
    def __sub__(self, arg: vec3d, /) -> mvec3d_u: ...

    def __iadd__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    def __isub__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    def __eq__(self, arg: mvec3d_u, /) -> bool: ...

    def __ne__(self, arg: mvec3d_u, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_u, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: mvec3d_e, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: pscalar3d, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: bivec3d, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: vec3d, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: scalar3d, /) -> mvec3d_u: ...

    def __rmul__(self, arg: float, /) -> mvec3d_u: ...

    def __truediv__(self, arg: float, /) -> mvec3d_u: ...

    def __imul__(self, arg: float, /) -> mvec3d_u: ...

    def __itruediv__(self, arg: float, /) -> mvec3d_u: ...

    def __rshift__(self, arg: scalar3d, /) -> mvec3d_u: ...

    def gr1(self) -> vec3d: ...

    def gr3(self) -> pscalar3d: ...

class mvec4d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: float, arg10: float, arg11: float, arg12: float, arg13: float, arg14: float, arg15: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar4d, /) -> None: ...

    @overload
    def __init__(self, arg: vec4d, /) -> None: ...

    @overload
    def __init__(self, arg: bivec4d, /) -> None: ...

    @overload
    def __init__(self, arg: trivec4d, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar4d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4d, arg1: bivec4d, arg2: pscalar4d, /) -> None: ...

    @overload
    def __init__(self, arg: mvec4d_e, /) -> None: ...

    @overload
    def __init__(self, arg0: vec4d, arg1: trivec4d, /) -> None: ...

    @overload
    def __init__(self, arg: mvec4d_u, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4d, arg1: vec4d, arg2: bivec4d, arg3: trivec4d, arg4: pscalar4d, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(16), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    @property
    def c4(self) -> float: ...

    @c4.setter
    def c4(self, arg: float, /) -> None: ...

    @property
    def c5(self) -> float: ...

    @c5.setter
    def c5(self, arg: float, /) -> None: ...

    @property
    def c6(self) -> float: ...

    @c6.setter
    def c6(self, arg: float, /) -> None: ...

    @property
    def c7(self) -> float: ...

    @c7.setter
    def c7(self, arg: float, /) -> None: ...

    @property
    def c8(self) -> float: ...

    @c8.setter
    def c8(self, arg: float, /) -> None: ...

    @property
    def c9(self) -> float: ...

    @c9.setter
    def c9(self, arg: float, /) -> None: ...

    @property
    def c10(self) -> float: ...

    @c10.setter
    def c10(self, arg: float, /) -> None: ...

    @property
    def c11(self) -> float: ...

    @c11.setter
    def c11(self, arg: float, /) -> None: ...

    @property
    def c12(self) -> float: ...

    @c12.setter
    def c12(self, arg: float, /) -> None: ...

    @property
    def c13(self) -> float: ...

    @c13.setter
    def c13(self, arg: float, /) -> None: ...

    @property
    def c14(self) -> float: ...

    @c14.setter
    def c14(self, arg: float, /) -> None: ...

    @property
    def c15(self) -> float: ...

    @c15.setter
    def c15(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(16))]: ...

    def __neg__(self) -> mvec4d: ...

    def __add__(self, arg: mvec4d, /) -> mvec4d: ...

    def __sub__(self, arg: mvec4d, /) -> mvec4d: ...

    def __iadd__(self, arg: mvec4d, /) -> mvec4d: ...

    def __isub__(self, arg: mvec4d, /) -> mvec4d: ...

    def __eq__(self, arg: mvec4d, /) -> bool: ...

    def __ne__(self, arg: mvec4d, /) -> bool: ...

    def __mul__(self, arg: float, /) -> mvec4d: ...

    def __rmul__(self, arg: float, /) -> mvec4d: ...

    def __truediv__(self, arg: float, /) -> mvec4d: ...

    def __imul__(self, arg: float, /) -> mvec4d: ...

    def __itruediv__(self, arg: float, /) -> mvec4d: ...

    def gr0(self) -> scalar4d: ...

    def gr1(self) -> vec4d: ...

    def gr2(self) -> bivec4d: ...

    def gr3(self) -> trivec4d: ...

    def gr4(self) -> pscalar4d: ...

class mvec4d_e:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar4d, /) -> None: ...

    @overload
    def __init__(self, arg: bivec4d, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar4d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4d, arg1: bivec4d, /) -> None: ...

    @overload
    def __init__(self, arg0: bivec4d, arg1: pscalar4d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4d, arg1: pscalar4d, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4d, arg1: bivec4d, arg2: pscalar4d, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(8), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    @property
    def c4(self) -> float: ...

    @c4.setter
    def c4(self, arg: float, /) -> None: ...

    @property
    def c5(self) -> float: ...

    @c5.setter
    def c5(self, arg: float, /) -> None: ...

    @property
    def c6(self) -> float: ...

    @c6.setter
    def c6(self, arg: float, /) -> None: ...

    @property
    def c7(self) -> float: ...

    @c7.setter
    def c7(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(8))]: ...

    def __neg__(self) -> mvec4d_e: ...

    def __add__(self, arg: mvec4d_e, /) -> mvec4d_e: ...

    def __sub__(self, arg: mvec4d_e, /) -> mvec4d_e: ...

    def __iadd__(self, arg: mvec4d_e, /) -> mvec4d_e: ...

    def __isub__(self, arg: mvec4d_e, /) -> mvec4d_e: ...

    def __eq__(self, arg: mvec4d_e, /) -> bool: ...

    def __ne__(self, arg: mvec4d_e, /) -> bool: ...

    def __mul__(self, arg: float, /) -> mvec4d_e: ...

    def __rmul__(self, arg: float, /) -> mvec4d_e: ...

    def __truediv__(self, arg: float, /) -> mvec4d_e: ...

    def __imul__(self, arg: float, /) -> mvec4d_e: ...

    def __itruediv__(self, arg: float, /) -> mvec4d_e: ...

    def gr0(self) -> scalar4d: ...

    def gr2(self) -> bivec4d: ...

    def gr4(self) -> pscalar4d: ...

class mvec4d_u:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> None: ...

    @overload
    def __init__(self, arg: vec4d, /) -> None: ...

    @overload
    def __init__(self, arg: trivec4d, /) -> None: ...

    @overload
    def __init__(self, arg0: vec4d, arg1: trivec4d, /) -> None: ...

    @overload
    def __init__(self, arg: mvec4d_u) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(8), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    @property
    def c4(self) -> float: ...

    @c4.setter
    def c4(self, arg: float, /) -> None: ...

    @property
    def c5(self) -> float: ...

    @c5.setter
    def c5(self, arg: float, /) -> None: ...

    @property
    def c6(self) -> float: ...

    @c6.setter
    def c6(self, arg: float, /) -> None: ...

    @property
    def c7(self) -> float: ...

    @c7.setter
    def c7(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(8))]: ...

    def __neg__(self) -> mvec4d_u: ...

    def __add__(self, arg: mvec4d_u, /) -> mvec4d_u: ...

    def __sub__(self, arg: mvec4d_u, /) -> mvec4d_u: ...

    def __iadd__(self, arg: mvec4d_u, /) -> mvec4d_u: ...

    def __isub__(self, arg: mvec4d_u, /) -> mvec4d_u: ...

    def __eq__(self, arg: mvec4d_u, /) -> bool: ...

    def __ne__(self, arg: mvec4d_u, /) -> bool: ...

    def __mul__(self, arg: float, /) -> mvec4d_u: ...

    def __rmul__(self, arg: float, /) -> mvec4d_u: ...

    def __truediv__(self, arg: float, /) -> mvec4d_u: ...

    def __imul__(self, arg: float, /) -> mvec4d_u: ...

    def __itruediv__(self, arg: float, /) -> mvec4d_u: ...

    def gr1(self) -> vec4d: ...

    def gr3(self) -> trivec4d: ...

class pscalar2d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> pscalar2d: ...

    @overload
    def __add__(self, arg: pscalar2d, /) -> pscalar2d: ...

    @overload
    def __add__(self, arg: scalar2d, /) -> mvec2d_e: ...

    @overload
    def __add__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __add__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: pscalar2d, /) -> pscalar2d: ...

    @overload
    def __sub__(self, arg: scalar2d, /) -> mvec2d_e: ...

    @overload
    def __sub__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __sub__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: float, /) -> pscalar2d: ...

    @overload
    def __mul__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __mul__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __mul__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __mul__(self, arg: scalar2d, /) -> pscalar2d: ...

    def __rmul__(self, arg: float, /) -> pscalar2d: ...

    def __truediv__(self, arg: float, /) -> pscalar2d: ...

    def __eq__(self, arg: pscalar2d, /) -> bool: ...

    def __ne__(self, arg: pscalar2d, /) -> bool: ...

    @overload
    def __lt__(self, arg: pscalar2d, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: pscalar2d, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: pscalar2d, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: pscalar2d, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

    @overload
    def __lshift__(self, arg: mvec2d, /) -> scalar2d: ...

    @overload
    def __lshift__(self, arg: mvec2d_e, /) -> scalar2d: ...

    @overload
    def __lshift__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __lshift__(self, arg: vec2d, /) -> scalar2d: ...

    @overload
    def __lshift__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __rshift__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __rshift__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __rshift__(self, arg: scalar2d, /) -> pscalar2d: ...

    @overload
    def __xor__(self, arg: mvec2d, /) -> pscalar2d: ...

    @overload
    def __xor__(self, arg: mvec2d_e, /) -> pscalar2d: ...

    @overload
    def __xor__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __xor__(self, arg: vec2d, /) -> scalar2d: ...

    @overload
    def __xor__(self, arg: scalar2d, /) -> pscalar2d: ...

class pscalar3d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> pscalar3d: ...

    @overload
    def __add__(self, arg: pscalar3d, /) -> pscalar3d: ...

    @overload
    def __add__(self, arg: vec3d, /) -> mvec3d_u: ...

    @overload
    def __add__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __add__(self, arg: scalar3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: pscalar3d, /) -> pscalar3d: ...

    @overload
    def __sub__(self, arg: vec3d, /) -> mvec3d_u: ...

    @overload
    def __sub__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __sub__(self, arg: scalar3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: float, /) -> pscalar3d: ...

    @overload
    def __mul__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_e, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: mvec3d_u, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __mul__(self, arg: bivec3d, /) -> vec3d: ...

    @overload
    def __mul__(self, arg: vec3d, /) -> bivec3d: ...

    @overload
    def __mul__(self, arg: scalar3d, /) -> pscalar3d: ...

    def __rmul__(self, arg: float, /) -> pscalar3d: ...

    def __truediv__(self, arg: float, /) -> pscalar3d: ...

    def __eq__(self, arg: pscalar3d, /) -> bool: ...

    def __ne__(self, arg: pscalar3d, /) -> bool: ...

    @overload
    def __lt__(self, arg: pscalar3d, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: pscalar3d, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: pscalar3d, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: pscalar3d, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

    @overload
    def __lshift__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __lshift__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __lshift__(self, arg: bivec3d, /) -> scalar3d: ...

    @overload
    def __lshift__(self, arg: vec3d, /) -> scalar3d: ...

    @overload
    def __lshift__(self, arg: scalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: bivec3d, /) -> vec3d: ...

    @overload
    def __rshift__(self, arg: vec3d, /) -> bivec3d: ...

    @overload
    def __rshift__(self, arg: scalar3d, /) -> pscalar3d: ...

    @overload
    def __xor__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __xor__(self, arg: bivec3d, /) -> scalar3d: ...

    @overload
    def __xor__(self, arg: vec3d, /) -> scalar3d: ...

    @overload
    def __xor__(self, arg: scalar3d, /) -> pscalar3d: ...

class pscalar4d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> pscalar4d: ...

    def __add__(self, arg: pscalar4d, /) -> pscalar4d: ...

    def __sub__(self, arg: pscalar4d, /) -> pscalar4d: ...

    def __mul__(self, arg: float, /) -> pscalar4d: ...

    def __rmul__(self, arg: float, /) -> pscalar4d: ...

    def __truediv__(self, arg: float, /) -> pscalar4d: ...

    def __eq__(self, arg: pscalar4d, /) -> bool: ...

    def __ne__(self, arg: pscalar4d, /) -> bool: ...

    @overload
    def __lt__(self, arg: pscalar4d, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: pscalar4d, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: pscalar4d, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: pscalar4d, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

class scalar2d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> scalar2d: ...

    @overload
    def __add__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __add__(self, arg: pscalar2d, /) -> mvec2d_e: ...

    @overload
    def __add__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __add__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __sub__(self, arg: pscalar2d, /) -> mvec2d_e: ...

    @overload
    def __sub__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __sub__(self, arg: vec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: float, /) -> scalar2d: ...

    @overload
    def __mul__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __mul__(self, arg: pscalar2d, /) -> pscalar2d: ...

    @overload
    def __mul__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __mul__(self, arg: scalar2d, /) -> scalar2d: ...

    def __rmul__(self, arg: float, /) -> scalar2d: ...

    def __truediv__(self, arg: float, /) -> scalar2d: ...

    def __eq__(self, arg: scalar2d, /) -> bool: ...

    def __ne__(self, arg: scalar2d, /) -> bool: ...

    @overload
    def __lt__(self, arg: scalar2d, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: scalar2d, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: scalar2d, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: scalar2d, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

    @overload
    def __lshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __lshift__(self, arg: pscalar2d, /) -> pscalar2d: ...

    @overload
    def __lshift__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __lshift__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: mvec2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: mvec2d_e, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: vec2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __xor__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __xor__(self, arg: mvec2d_e, /) -> mvec2d_e: ...

    @overload
    def __xor__(self, arg: pscalar2d, /) -> pscalar2d: ...

    @overload
    def __xor__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __xor__(self, arg: scalar2d, /) -> scalar2d: ...

class scalar3d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> scalar3d: ...

    @overload
    def __add__(self, arg: scalar3d, /) -> scalar3d: ...

    @overload
    def __add__(self, arg: bivec3d, /) -> mvec3d_e: ...

    @overload
    def __add__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __add__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: pscalar3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: scalar3d, /) -> scalar3d: ...

    @overload
    def __sub__(self, arg: bivec3d, /) -> mvec3d_e: ...

    @overload
    def __sub__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __sub__(self, arg: vec3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: pscalar3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: float, /) -> scalar3d: ...

    @overload
    def __mul__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: pscalar3d, /) -> pscalar3d: ...

    @overload
    def __mul__(self, arg: bivec3d, /) -> bivec3d: ...

    @overload
    def __mul__(self, arg: vec3d, /) -> vec3d: ...

    @overload
    def __mul__(self, arg: scalar3d, /) -> scalar3d: ...

    def __rmul__(self, arg: float, /) -> scalar3d: ...

    def __truediv__(self, arg: float, /) -> scalar3d: ...

    def __eq__(self, arg: scalar3d, /) -> bool: ...

    def __ne__(self, arg: scalar3d, /) -> bool: ...

    @overload
    def __lt__(self, arg: scalar3d, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: scalar3d, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: scalar3d, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: scalar3d, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

    @overload
    def __lshift__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __lshift__(self, arg: mvec3d_e, /) -> mvec3d_e: ...

    @overload
    def __lshift__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __lshift__(self, arg: pscalar3d, /) -> pscalar3d: ...

    @overload
    def __lshift__(self, arg: bivec3d, /) -> bivec3d: ...

    @overload
    def __lshift__(self, arg: vec3d, /) -> vec3d: ...

    @overload
    def __lshift__(self, arg: scalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: bivec3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: vec3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: scalar3d, /) -> scalar3d: ...

    @overload
    def __xor__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: pscalar3d, /) -> pscalar3d: ...

    @overload
    def __xor__(self, arg: bivec3d, /) -> bivec3d: ...

    @overload
    def __xor__(self, arg: vec3d, /) -> vec3d: ...

    @overload
    def __xor__(self, arg: scalar3d, /) -> scalar3d: ...

class scalar4d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> scalar4d: ...

    @overload
    def __add__(self, arg: scalar4d, /) -> scalar4d: ...

    @overload
    def __add__(self, arg: bivec4d, /) -> mvec4d_e: ...

    @overload
    def __sub__(self, arg: scalar4d, /) -> scalar4d: ...

    @overload
    def __sub__(self, arg: bivec4d, /) -> mvec4d_e: ...

    def __mul__(self, arg: float, /) -> scalar4d: ...

    def __rmul__(self, arg: float, /) -> scalar4d: ...

    def __truediv__(self, arg: float, /) -> scalar4d: ...

    def __eq__(self, arg: scalar4d, /) -> bool: ...

    def __ne__(self, arg: scalar4d, /) -> bool: ...

    @overload
    def __lt__(self, arg: scalar4d, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: scalar4d, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: scalar4d, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: scalar4d, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

class trivec4d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C', device='cpu')], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def z(self) -> float: ...

    @z.setter
    def z(self, arg: float, /) -> None: ...

    @property
    def w(self) -> float: ...

    @w.setter
    def w(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(4))]: ...

    def __neg__(self) -> trivec4d: ...

    @overload
    def __add__(self, arg: trivec4d, /) -> trivec4d: ...

    @overload
    def __add__(self, arg: vec4d, /) -> mvec4d_u: ...

    @overload
    def __sub__(self, arg: trivec4d, /) -> trivec4d: ...

    @overload
    def __sub__(self, arg: vec4d, /) -> mvec4d_u: ...

    def __iadd__(self, arg: trivec4d, /) -> trivec4d: ...

    def __isub__(self, arg: trivec4d, /) -> trivec4d: ...

    def __eq__(self, arg: trivec4d, /) -> bool: ...

    def __ne__(self, arg: trivec4d, /) -> bool: ...

    def __mul__(self, arg: float, /) -> trivec4d: ...

    def __rmul__(self, arg: float, /) -> trivec4d: ...

    def __truediv__(self, arg: float, /) -> trivec4d: ...

    def __imul__(self, arg: float, /) -> trivec4d: ...

    def __itruediv__(self, arg: float, /) -> trivec4d: ...

class vec2d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(2), order='C', device='cpu')], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(2))]: ...

    def __neg__(self) -> vec2d: ...

    @overload
    def __add__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __add__(self, arg: scalar2d, /) -> mvec2d: ...

    @overload
    def __add__(self, arg: pscalar2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: vec2d, /) -> vec2d: ...

    @overload
    def __sub__(self, arg: scalar2d, /) -> mvec2d: ...

    @overload
    def __sub__(self, arg: pscalar2d, /) -> mvec2d: ...

    def __iadd__(self, arg: vec2d, /) -> vec2d: ...

    def __isub__(self, arg: vec2d, /) -> vec2d: ...

    def __eq__(self, arg: vec2d, /) -> bool: ...

    def __ne__(self, arg: vec2d, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> vec2d: ...

    @overload
    def __mul__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __mul__(self, arg: mvec2d_e, /) -> vec2d: ...

    @overload
    def __mul__(self, arg: pscalar2d, /) -> vec2d: ...

    @overload
    def __mul__(self, arg: vec2d, /) -> mvec2d_e: ...

    @overload
    def __mul__(self, arg: scalar2d, /) -> vec2d: ...

    def __rmul__(self, arg: float, /) -> vec2d: ...

    def __truediv__(self, arg: float, /) -> vec2d: ...

    def __imul__(self, arg: float, /) -> vec2d: ...

    def __itruediv__(self, arg: float, /) -> vec2d: ...

    @overload
    def __lshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __lshift__(self, arg: mvec2d_e, /) -> vec2d: ...

    @overload
    def __lshift__(self, arg: pscalar2d, /) -> vec2d: ...

    @overload
    def __lshift__(self, arg: vec2d, /) -> scalar2d: ...

    @overload
    def __lshift__(self, arg: scalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __rshift__(self, arg: mvec2d_e, /) -> vec2d: ...

    @overload
    def __rshift__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: vec2d, /) -> scalar2d: ...

    @overload
    def __rshift__(self, arg: scalar2d, /) -> vec2d: ...

    @overload
    def __xor__(self, arg: mvec2d, /) -> mvec2d: ...

    @overload
    def __xor__(self, arg: mvec2d_e, /) -> vec2d: ...

    @overload
    def __xor__(self, arg: pscalar2d, /) -> scalar2d: ...

    @overload
    def __xor__(self, arg: vec2d, /) -> pscalar2d: ...

    @overload
    def __xor__(self, arg: scalar2d, /) -> vec2d: ...

class vec3d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C', device='cpu')], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def z(self) -> float: ...

    @z.setter
    def z(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(3))]: ...

    def __neg__(self) -> vec3d: ...

    @overload
    def __add__(self, arg: vec3d, /) -> vec3d: ...

    @overload
    def __add__(self, arg: pscalar3d, /) -> mvec3d_u: ...

    @overload
    def __add__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __add__(self, arg: scalar3d, /) -> mvec3d: ...

    @overload
    def __add__(self, arg: bivec3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: vec3d, /) -> vec3d: ...

    @overload
    def __sub__(self, arg: pscalar3d, /) -> mvec3d_u: ...

    @overload
    def __sub__(self, arg: mvec3d_u, /) -> mvec3d_u: ...

    @overload
    def __sub__(self, arg: scalar3d, /) -> mvec3d: ...

    @overload
    def __sub__(self, arg: bivec3d, /) -> mvec3d: ...

    def __iadd__(self, arg: vec3d, /) -> vec3d: ...

    def __isub__(self, arg: vec3d, /) -> vec3d: ...

    def __eq__(self, arg: vec3d, /) -> bool: ...

    def __ne__(self, arg: vec3d, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> vec3d: ...

    @overload
    def __mul__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __mul__(self, arg: mvec3d_e, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: mvec3d_u, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: pscalar3d, /) -> bivec3d: ...

    @overload
    def __mul__(self, arg: bivec3d, /) -> mvec3d_u: ...

    @overload
    def __mul__(self, arg: vec3d, /) -> mvec3d_e: ...

    @overload
    def __mul__(self, arg: scalar3d, /) -> vec3d: ...

    def __rmul__(self, arg: float, /) -> vec3d: ...

    def __truediv__(self, arg: float, /) -> vec3d: ...

    def __imul__(self, arg: float, /) -> vec3d: ...

    def __itruediv__(self, arg: float, /) -> vec3d: ...

    @overload
    def __lshift__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __lshift__(self, arg: pscalar3d, /) -> bivec3d: ...

    @overload
    def __lshift__(self, arg: bivec3d, /) -> vec3d: ...

    @overload
    def __lshift__(self, arg: vec3d, /) -> scalar3d: ...

    @overload
    def __lshift__(self, arg: scalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: bivec3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: vec3d, /) -> scalar3d: ...

    @overload
    def __rshift__(self, arg: scalar3d, /) -> vec3d: ...

    @overload
    def __xor__(self, arg: mvec3d, /) -> mvec3d: ...

    @overload
    def __xor__(self, arg: pscalar3d, /) -> scalar3d: ...

    @overload
    def __xor__(self, arg: bivec3d, /) -> pscalar3d: ...

    @overload
    def __xor__(self, arg: vec3d, /) -> bivec3d: ...

    @overload
    def __xor__(self, arg: scalar3d, /) -> vec3d: ...

class vec4d:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C', device='cpu')], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def z(self) -> float: ...

    @z.setter
    def z(self, arg: float, /) -> None: ...

    @property
    def w(self) -> float: ...

    @w.setter
    def w(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(4))]: ...

    def __neg__(self) -> vec4d: ...

    @overload
    def __add__(self, arg: vec4d, /) -> vec4d: ...

    @overload
    def __add__(self, arg: trivec4d, /) -> mvec4d_u: ...

    @overload
    def __sub__(self, arg: vec4d, /) -> vec4d: ...

    @overload
    def __sub__(self, arg: trivec4d, /) -> mvec4d_u: ...

    def __iadd__(self, arg: vec4d, /) -> vec4d: ...

    def __isub__(self, arg: vec4d, /) -> vec4d: ...

    def __eq__(self, arg: vec4d, /) -> bool: ...

    def __ne__(self, arg: vec4d, /) -> bool: ...

    def __mul__(self, arg: float, /) -> vec4d: ...

    def __rmul__(self, arg: float, /) -> vec4d: ...

    def __truediv__(self, arg: float, /) -> vec4d: ...

    def __imul__(self, arg: float, /) -> vec4d: ...

    def __itruediv__(self, arg: float, /) -> vec4d: ...

@overload
def angle(arg0: vec2d, arg1: vec2d, /) -> float: ...

@overload
def angle(arg0: vec3d, arg1: vec3d, /) -> float: ...

@overload
def angle(arg0: bivec3d, arg1: bivec3d, /) -> float: ...

@overload
def angle(arg0: vec3d, arg1: bivec3d, /) -> float: ...

@overload
def angle(arg0: bivec3d, arg1: vec3d, /) -> float: ...

def angle_to_re(arg: mvec2d_e, /) -> float: ...

@overload
def cmpl(arg: scalar3d, /) -> pscalar3d: ...

@overload
def cmpl(arg: vec3d, /) -> bivec3d: ...

@overload
def cmpl(arg: bivec3d, /) -> vec3d: ...

@overload
def cmpl(arg: pscalar3d, /) -> scalar3d: ...

@overload
def cmpl(arg: mvec3d_e, /) -> mvec3d_u: ...

@overload
def cmpl(arg: mvec3d_u, /) -> mvec3d_e: ...

@overload
def cmpl(arg: mvec3d, /) -> mvec3d: ...

@overload
def cmt(arg0: mvec2d, arg1: mvec2d, /) -> mvec2d: ...

@overload
def cmt(arg0: pscalar2d, arg1: vec2d, /) -> vec2d: ...

@overload
def cmt(arg0: vec2d, arg1: pscalar2d, /) -> vec2d: ...

@overload
def cmt(arg0: vec2d, arg1: vec2d, /) -> pscalar2d: ...

@overload
def cmt(arg0: mvec3d, arg1: mvec3d, /) -> mvec3d: ...

@overload
def cmt(arg0: bivec3d, arg1: bivec3d, /) -> bivec3d: ...

@overload
def cmt(arg0: bivec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def cmt(arg0: vec3d, arg1: bivec3d, /) -> vec3d: ...

@overload
def cmt(arg0: vec3d, arg1: vec3d, /) -> bivec3d: ...

@overload
def conj(arg: scalar2d, /) -> scalar2d: ...

@overload
def conj(arg: vec2d, /) -> vec2d: ...

@overload
def conj(arg: pscalar2d, /) -> pscalar2d: ...

@overload
def conj(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def conj(arg: mvec2d, /) -> mvec2d: ...

@overload
def conj(arg: scalar3d, /) -> scalar3d: ...

@overload
def conj(arg: vec3d, /) -> vec3d: ...

@overload
def conj(arg: bivec3d, /) -> bivec3d: ...

@overload
def conj(arg: pscalar3d, /) -> pscalar3d: ...

@overload
def conj(arg: mvec3d_e, /) -> mvec3d_e: ...

@overload
def conj(arg: mvec3d_u, /) -> mvec3d_u: ...

@overload
def conj(arg: mvec3d, /) -> mvec3d: ...

def cross(arg0: vec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def dot(arg0: mvec2d, arg1: mvec2d, /) -> scalar2d: ...

@overload
def dot(arg0: pscalar2d, arg1: pscalar2d, /) -> scalar2d: ...

@overload
def dot(arg0: vec2d, arg1: vec2d, /) -> scalar2d: ...

@overload
def dot(arg0: scalar2d, arg1: scalar2d, /) -> scalar2d: ...

@overload
def dot(arg0: mvec3d, arg1: mvec3d, /) -> scalar3d: ...

@overload
def dot(arg0: pscalar3d, arg1: pscalar3d, /) -> scalar3d: ...

@overload
def dot(arg0: bivec3d, arg1: bivec3d, /) -> scalar3d: ...

@overload
def dot(arg0: vec3d, arg1: vec3d, /) -> scalar3d: ...

@overload
def dot(arg0: scalar3d, arg1: scalar3d, /) -> scalar3d: ...

@overload
def dual(arg: scalar3d, /) -> pscalar3d: ...

@overload
def dual(arg: vec3d, /) -> bivec3d: ...

@overload
def dual(arg: bivec3d, /) -> vec3d: ...

@overload
def dual(arg: pscalar3d, /) -> scalar3d: ...

@overload
def dual(arg: mvec3d_e, /) -> mvec3d_u: ...

@overload
def dual(arg: mvec3d_u, /) -> mvec3d_e: ...

@overload
def dual(arg: mvec3d, /) -> mvec3d: ...

@overload
def exp(arg: pscalar2d, /) -> mvec2d_e: ...

@overload
def exp(arg0: pscalar2d, arg1: float, /) -> mvec2d_e: ...

@overload
def exp(arg: bivec3d, /) -> mvec3d_e: ...

@overload
def exp(arg0: bivec3d, arg1: float, /) -> mvec3d_e: ...

@overload
def get_rotor(arg0: pscalar2d, arg1: float, /) -> mvec2d_e: ...

@overload
def get_rotor(arg0: bivec3d, arg1: float, /) -> mvec3d_e: ...

@overload
def gr_inv(arg: scalar2d, /) -> scalar2d: ...

@overload
def gr_inv(arg: vec2d, /) -> vec2d: ...

@overload
def gr_inv(arg: pscalar2d, /) -> pscalar2d: ...

@overload
def gr_inv(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def gr_inv(arg: mvec2d, /) -> mvec2d: ...

@overload
def gr_inv(arg: scalar3d, /) -> scalar3d: ...

@overload
def gr_inv(arg: vec3d, /) -> vec3d: ...

@overload
def gr_inv(arg: bivec3d, /) -> bivec3d: ...

@overload
def gr_inv(arg: pscalar3d, /) -> pscalar3d: ...

@overload
def gr_inv(arg: mvec3d_e, /) -> mvec3d_e: ...

@overload
def gr_inv(arg: mvec3d_u, /) -> mvec3d_u: ...

@overload
def gr_inv(arg: mvec3d, /) -> mvec3d: ...

@overload
def gs_orthogonal(arg0: vec2d, arg1: vec2d, /) -> list[vec2d]: ...

@overload
def gs_orthogonal(arg0: vec3d, arg1: vec3d, /) -> list[vec3d]: ...

@overload
def gs_orthogonal(arg0: vec3d, arg1: vec3d, arg2: vec3d, /) -> list[vec3d]: ...

@overload
def gs_orthonormal(arg0: vec2d, arg1: vec2d, /) -> list[vec2d]: ...

@overload
def gs_orthonormal(arg0: vec3d, arg1: vec3d, /) -> list[vec3d]: ...

@overload
def gs_orthonormal(arg0: vec3d, arg1: vec3d, arg2: vec3d, /) -> list[vec3d]: ...

@overload
def inv(arg: scalar2d, /) -> scalar2d: ...

@overload
def inv(arg: vec2d, /) -> vec2d: ...

@overload
def inv(arg: pscalar2d, /) -> pscalar2d: ...

@overload
def inv(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def inv(arg: mvec2d, /) -> mvec2d: ...

@overload
def inv(arg: scalar3d, /) -> scalar3d: ...

@overload
def inv(arg: vec3d, /) -> vec3d: ...

@overload
def inv(arg: bivec3d, /) -> bivec3d: ...

@overload
def inv(arg: pscalar3d, /) -> pscalar3d: ...

@overload
def inv(arg: mvec3d_e, /) -> mvec3d_e: ...

@overload
def inv(arg: mvec3d_u, /) -> mvec3d_u: ...

@overload
def inv(arg: mvec3d, /) -> mvec3d: ...

@overload
def is_congruent(arg0: scalar2d, arg1: scalar2d, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: vec2d, arg1: vec2d, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: pscalar2d, arg1: pscalar2d, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: scalar3d, arg1: scalar3d, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: vec3d, arg1: vec3d, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: bivec3d, arg1: bivec3d, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: pscalar3d, arg1: pscalar3d, arg2: float, /) -> bool: ...

@overload
def l_cmpl(arg: scalar2d, /) -> pscalar2d: ...

@overload
def l_cmpl(arg: vec2d, /) -> vec2d: ...

@overload
def l_cmpl(arg: pscalar2d, /) -> scalar2d: ...

@overload
def l_cmpl(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def l_cmpl(arg: mvec2d, /) -> mvec2d: ...

@overload
def l_dual(arg: scalar2d, /) -> pscalar2d: ...

@overload
def l_dual(arg: vec2d, /) -> vec2d: ...

@overload
def l_dual(arg: pscalar2d, /) -> scalar2d: ...

@overload
def l_dual(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def l_dual(arg: mvec2d, /) -> mvec2d: ...

@overload
def normalize(arg: scalar2d, /) -> scalar2d: ...

@overload
def normalize(arg: vec2d, /) -> vec2d: ...

@overload
def normalize(arg: pscalar2d, /) -> pscalar2d: ...

@overload
def normalize(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def normalize(arg: mvec2d, /) -> mvec2d: ...

@overload
def normalize(arg: scalar3d, /) -> scalar3d: ...

@overload
def normalize(arg: vec3d, /) -> vec3d: ...

@overload
def normalize(arg: bivec3d, /) -> bivec3d: ...

@overload
def normalize(arg: pscalar3d, /) -> pscalar3d: ...

@overload
def normalize(arg: mvec3d_e, /) -> mvec3d_e: ...

@overload
def normalize(arg: mvec3d_u, /) -> mvec3d_u: ...

@overload
def normalize(arg: mvec3d, /) -> mvec3d: ...

@overload
def nrm(arg: scalar2d, /) -> float: ...

@overload
def nrm(arg: vec2d, /) -> float: ...

@overload
def nrm(arg: pscalar2d, /) -> float: ...

@overload
def nrm(arg: mvec2d_e, /) -> float: ...

@overload
def nrm(arg: mvec2d, /) -> float: ...

@overload
def nrm(arg: scalar3d, /) -> float: ...

@overload
def nrm(arg: vec3d, /) -> float: ...

@overload
def nrm(arg: bivec3d, /) -> float: ...

@overload
def nrm(arg: pscalar3d, /) -> float: ...

@overload
def nrm(arg: mvec3d_e, /) -> float: ...

@overload
def nrm(arg: mvec3d_u, /) -> float: ...

@overload
def nrm(arg: mvec3d, /) -> float: ...

@overload
def nrm_sq(arg: scalar2d, /) -> float: ...

@overload
def nrm_sq(arg: vec2d, /) -> float: ...

@overload
def nrm_sq(arg: pscalar2d, /) -> float: ...

@overload
def nrm_sq(arg: mvec2d_e, /) -> float: ...

@overload
def nrm_sq(arg: mvec2d, /) -> float: ...

@overload
def nrm_sq(arg: scalar3d, /) -> float: ...

@overload
def nrm_sq(arg: vec3d, /) -> float: ...

@overload
def nrm_sq(arg: bivec3d, /) -> float: ...

@overload
def nrm_sq(arg: pscalar3d, /) -> float: ...

@overload
def nrm_sq(arg: mvec3d_e, /) -> float: ...

@overload
def nrm_sq(arg: mvec3d_u, /) -> float: ...

@overload
def nrm_sq(arg: mvec3d, /) -> float: ...

@overload
def project_onto(arg0: vec2d, arg1: vec2d, /) -> vec2d: ...

@overload
def project_onto(arg0: vec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def project_onto(arg0: vec3d, arg1: bivec3d, /) -> vec3d: ...

@overload
def r_cmpl(arg: scalar2d, /) -> pscalar2d: ...

@overload
def r_cmpl(arg: vec2d, /) -> vec2d: ...

@overload
def r_cmpl(arg: pscalar2d, /) -> scalar2d: ...

@overload
def r_cmpl(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def r_cmpl(arg: mvec2d, /) -> mvec2d: ...

@overload
def r_dual(arg: scalar2d, /) -> pscalar2d: ...

@overload
def r_dual(arg: vec2d, /) -> vec2d: ...

@overload
def r_dual(arg: pscalar2d, /) -> scalar2d: ...

@overload
def r_dual(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def r_dual(arg: mvec2d, /) -> mvec2d: ...

@overload
def reflect_on(arg0: vec2d, arg1: vec2d, /) -> vec2d: ...

@overload
def reflect_on(arg0: vec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def reflect_on(arg0: vec3d, arg1: bivec3d, /) -> vec3d: ...

@overload
def reflect_on(arg0: bivec3d, arg1: bivec3d, /) -> bivec3d: ...

@overload
def reflect_on_vec(arg0: vec2d, arg1: vec2d, /) -> vec2d: ...

@overload
def reflect_on_vec(arg0: vec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def reject_from(arg0: vec2d, arg1: vec2d, /) -> vec2d: ...

@overload
def reject_from(arg0: vec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def reject_from(arg0: vec3d, arg1: bivec3d, /) -> vec3d: ...

@overload
def rev(arg: scalar2d, /) -> scalar2d: ...

@overload
def rev(arg: vec2d, /) -> vec2d: ...

@overload
def rev(arg: pscalar2d, /) -> pscalar2d: ...

@overload
def rev(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def rev(arg: mvec2d, /) -> mvec2d: ...

@overload
def rev(arg: scalar3d, /) -> scalar3d: ...

@overload
def rev(arg: vec3d, /) -> vec3d: ...

@overload
def rev(arg: bivec3d, /) -> bivec3d: ...

@overload
def rev(arg: pscalar3d, /) -> pscalar3d: ...

@overload
def rev(arg: mvec3d_e, /) -> mvec3d_e: ...

@overload
def rev(arg: mvec3d_u, /) -> mvec3d_u: ...

@overload
def rev(arg: mvec3d, /) -> mvec3d: ...

@overload
def rotate(arg0: vec2d, arg1: mvec2d_e, /) -> vec2d: ...

@overload
def rotate(arg0: mvec2d, arg1: mvec2d_e, /) -> mvec2d: ...

@overload
def rotate(arg0: vec3d, arg1: mvec3d_e, /) -> vec3d: ...

@overload
def rotate(arg0: bivec3d, arg1: mvec3d_e, /) -> bivec3d: ...

@overload
def rotate(arg0: mvec3d, arg1: mvec3d_e, /) -> mvec3d: ...

@overload
def rotate_opt(arg0: vec2d, arg1: mvec2d_e, /) -> vec2d: ...

@overload
def rotate_opt(arg0: Sequence[vec2d], arg1: mvec2d_e, /) -> list[vec2d]: ...

@overload
def rotate_opt(arg0: vec3d, arg1: mvec3d_e, /) -> vec3d: ...

@overload
def rotate_opt(arg0: Sequence[vec3d], arg1: mvec3d_e, /) -> list[vec3d]: ...

@overload
def rotate_opt(arg0: bivec3d, arg1: mvec3d_e, /) -> bivec3d: ...

@overload
def rotate_opt(arg0: Sequence[bivec3d], arg1: mvec3d_e, /) -> list[bivec3d]: ...

@overload
def rtwdg1(arg0: vec2d, arg1: vec2d, /) -> pscalar2d: ...

@overload
def rtwdg1(arg0: vec2d, arg1: scalar2d, /) -> vec2d: ...

@overload
def rtwdg1(arg0: scalar2d, arg1: vec2d, /) -> vec2d: ...

@overload
def rtwdg1(arg0: bivec3d, arg1: bivec3d, /) -> pscalar3d: ...

@overload
def rtwdg1(arg0: bivec3d, arg1: vec3d, /) -> bivec3d: ...

@overload
def rtwdg1(arg0: vec3d, arg1: bivec3d, /) -> bivec3d: ...

@overload
def rtwdg1(arg0: bivec3d, arg1: scalar3d, /) -> vec3d: ...

@overload
def rtwdg1(arg0: scalar3d, arg1: bivec3d, /) -> vec3d: ...

@overload
def rtwdg1(arg0: vec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def rwdg(arg0: mvec2d, arg1: mvec2d, /) -> mvec2d: ...

@overload
def rwdg(arg0: pscalar2d, arg1: pscalar2d, /) -> pscalar2d: ...

@overload
def rwdg(arg0: pscalar2d, arg1: vec2d, /) -> vec2d: ...

@overload
def rwdg(arg0: vec2d, arg1: pscalar2d, /) -> vec2d: ...

@overload
def rwdg(arg0: pscalar2d, arg1: scalar2d, /) -> scalar2d: ...

@overload
def rwdg(arg0: scalar2d, arg1: pscalar2d, /) -> scalar2d: ...

@overload
def rwdg(arg0: vec2d, arg1: vec2d, /) -> scalar2d: ...

@overload
def rwdg(arg0: vec2d, arg1: scalar2d, /) -> scalar2d: ...

@overload
def rwdg(arg0: scalar2d, arg1: vec2d, /) -> scalar2d: ...

@overload
def rwdg(arg0: scalar2d, arg1: scalar2d, /) -> scalar2d: ...

@overload
def rwdg(arg0: mvec3d, arg1: mvec3d, /) -> mvec3d: ...

@overload
def rwdg(arg0: pscalar3d, arg1: pscalar3d, /) -> pscalar3d: ...

@overload
def rwdg(arg0: pscalar3d, arg1: bivec3d, /) -> bivec3d: ...

@overload
def rwdg(arg0: bivec3d, arg1: pscalar3d, /) -> bivec3d: ...

@overload
def rwdg(arg0: pscalar3d, arg1: vec3d, /) -> vec3d: ...

@overload
def rwdg(arg0: vec3d, arg1: pscalar3d, /) -> vec3d: ...

@overload
def rwdg(arg0: pscalar3d, arg1: scalar3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: scalar3d, arg1: pscalar3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: bivec3d, arg1: bivec3d, /) -> vec3d: ...

@overload
def rwdg(arg0: bivec3d, arg1: vec3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: vec3d, arg1: bivec3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: bivec3d, arg1: scalar3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: scalar3d, arg1: bivec3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: vec3d, arg1: vec3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: vec3d, arg1: scalar3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: scalar3d, arg1: vec3d, /) -> scalar3d: ...

@overload
def rwdg(arg0: scalar3d, arg1: scalar3d, /) -> scalar3d: ...

@overload
def sqrt(arg: mvec2d_e, /) -> mvec2d_e: ...

@overload
def sqrt(arg: mvec3d_e, /) -> mvec3d_e: ...

@overload
def twdg1(arg0: pscalar2d, arg1: vec2d, /) -> vec2d: ...

@overload
def twdg1(arg0: vec2d, arg1: pscalar2d, /) -> vec2d: ...

@overload
def twdg1(arg0: vec2d, arg1: vec2d, /) -> scalar2d: ...

@overload
def twdg1(arg0: pscalar3d, arg1: vec3d, /) -> bivec3d: ...

@overload
def twdg1(arg0: vec3d, arg1: pscalar3d, /) -> bivec3d: ...

@overload
def twdg1(arg0: bivec3d, arg1: bivec3d, /) -> bivec3d: ...

@overload
def twdg1(arg0: bivec3d, arg1: vec3d, /) -> vec3d: ...

@overload
def twdg1(arg0: vec3d, arg1: bivec3d, /) -> vec3d: ...

@overload
def twdg1(arg0: vec3d, arg1: vec3d, /) -> scalar3d: ...

@overload
def wdg(arg0: mvec2d, arg1: mvec2d, /) -> mvec2d: ...

@overload
def wdg(arg0: mvec2d, arg1: mvec2d_e, /) -> mvec2d: ...

@overload
def wdg(arg0: mvec2d_e, arg1: mvec2d, /) -> mvec2d: ...

@overload
def wdg(arg0: mvec2d, arg1: pscalar2d, /) -> pscalar2d: ...

@overload
def wdg(arg0: pscalar2d, arg1: mvec2d, /) -> pscalar2d: ...

@overload
def wdg(arg0: mvec2d, arg1: vec2d, /) -> mvec2d: ...

@overload
def wdg(arg0: vec2d, arg1: mvec2d, /) -> mvec2d: ...

@overload
def wdg(arg0: mvec2d, arg1: scalar2d, /) -> mvec2d: ...

@overload
def wdg(arg0: scalar2d, arg1: mvec2d, /) -> mvec2d: ...

@overload
def wdg(arg0: mvec2d_e, arg1: mvec2d_e, /) -> mvec2d_e: ...

@overload
def wdg(arg0: mvec2d_e, arg1: pscalar2d, /) -> pscalar2d: ...

@overload
def wdg(arg0: pscalar2d, arg1: mvec2d_e, /) -> pscalar2d: ...

@overload
def wdg(arg0: mvec2d_e, arg1: vec2d, /) -> vec2d: ...

@overload
def wdg(arg0: vec2d, arg1: mvec2d_e, /) -> vec2d: ...

@overload
def wdg(arg0: mvec2d_e, arg1: scalar2d, /) -> mvec2d_e: ...

@overload
def wdg(arg0: scalar2d, arg1: mvec2d_e, /) -> mvec2d_e: ...

@overload
def wdg(arg0: pscalar2d, arg1: pscalar2d, /) -> scalar2d: ...

@overload
def wdg(arg0: pscalar2d, arg1: vec2d, /) -> scalar2d: ...

@overload
def wdg(arg0: vec2d, arg1: pscalar2d, /) -> scalar2d: ...

@overload
def wdg(arg0: pscalar2d, arg1: scalar2d, /) -> pscalar2d: ...

@overload
def wdg(arg0: scalar2d, arg1: pscalar2d, /) -> pscalar2d: ...

@overload
def wdg(arg0: vec2d, arg1: vec2d, /) -> pscalar2d: ...

@overload
def wdg(arg0: vec2d, arg1: scalar2d, /) -> vec2d: ...

@overload
def wdg(arg0: scalar2d, arg1: vec2d, /) -> vec2d: ...

@overload
def wdg(arg0: scalar2d, arg1: scalar2d, /) -> scalar2d: ...

@overload
def wdg(arg0: mvec3d, arg1: mvec3d, /) -> mvec3d: ...

@overload
def wdg(arg0: mvec3d, arg1: pscalar3d, /) -> mvec3d: ...

@overload
def wdg(arg0: pscalar3d, arg1: mvec3d, /) -> mvec3d: ...

@overload
def wdg(arg0: mvec3d, arg1: bivec3d, /) -> mvec3d: ...

@overload
def wdg(arg0: bivec3d, arg1: mvec3d, /) -> mvec3d: ...

@overload
def wdg(arg0: mvec3d, arg1: vec3d, /) -> mvec3d: ...

@overload
def wdg(arg0: vec3d, arg1: mvec3d, /) -> mvec3d: ...

@overload
def wdg(arg0: mvec3d, arg1: scalar3d, /) -> mvec3d: ...

@overload
def wdg(arg0: scalar3d, arg1: mvec3d, /) -> mvec3d: ...

@overload
def wdg(arg0: pscalar3d, arg1: pscalar3d, /) -> scalar3d: ...

@overload
def wdg(arg0: pscalar3d, arg1: bivec3d, /) -> scalar3d: ...

@overload
def wdg(arg0: bivec3d, arg1: pscalar3d, /) -> scalar3d: ...

@overload
def wdg(arg0: pscalar3d, arg1: vec3d, /) -> scalar3d: ...

@overload
def wdg(arg0: vec3d, arg1: pscalar3d, /) -> scalar3d: ...

@overload
def wdg(arg0: pscalar3d, arg1: scalar3d, /) -> pscalar3d: ...

@overload
def wdg(arg0: scalar3d, arg1: pscalar3d, /) -> pscalar3d: ...

@overload
def wdg(arg0: bivec3d, arg1: bivec3d, /) -> scalar3d: ...

@overload
def wdg(arg0: bivec3d, arg1: vec3d, /) -> pscalar3d: ...

@overload
def wdg(arg0: vec3d, arg1: bivec3d, /) -> pscalar3d: ...

@overload
def wdg(arg0: bivec3d, arg1: scalar3d, /) -> bivec3d: ...

@overload
def wdg(arg0: scalar3d, arg1: bivec3d, /) -> bivec3d: ...

@overload
def wdg(arg0: vec3d, arg1: vec3d, /) -> bivec3d: ...

@overload
def wdg(arg0: vec3d, arg1: scalar3d, /) -> vec3d: ...

@overload
def wdg(arg0: scalar3d, arg1: vec3d, /) -> vec3d: ...

@overload
def wdg(arg0: scalar3d, arg1: scalar3d, /) -> scalar3d: ...

I_2d: pscalar2d = ...

I_2d_mv: mvec2d = ...

I_2d_mv_e: mvec2d_e = ...

I_3d: pscalar3d = ...

I_3d_mv: mvec3d = ...

I_3d_mv_u: mvec3d_u = ...

O_2d: vec2d = ...

O_3d: vec3d = ...

e123_3d: pscalar3d = ...

e12_2d: pscalar2d = ...

e12_3d: bivec3d = ...

e12_3d_mv: mvec3d = ...

e12_3d_mv_e: mvec3d_e = ...

e1_2d: vec2d = ...

e1_2d_mv: mvec2d = ...

e1_3d: vec3d = ...

e1_3d_mv: mvec3d = ...

e23_3d: bivec3d = ...

e23_3d_mv: mvec3d = ...

e23_3d_mv_e: mvec3d_e = ...

e2_2d: vec2d = ...

e2_2d_mv: mvec2d = ...

e2_3d: vec3d = ...

e2_3d_mv: mvec3d = ...

e31_3d: bivec3d = ...

e31_3d_mv: mvec3d = ...

e31_3d_mv_e: mvec3d_e = ...

e3_3d: vec3d = ...

e3_3d_mv: mvec3d = ...

x_dir_2d: vec2d = ...

x_dir_3d: vec3d = ...

xy_3d: bivec3d = ...

y_dir_2d: vec2d = ...

y_dir_3d: vec3d = ...

yz_3d: bivec3d = ...

z_dir_3d: vec3d = ...

zx_3d: bivec3d = ...
