"""Space-time algebra (G(1,3,0), types *_4ds)"""

from collections.abc import Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


class bivec4ds:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C', device='cpu')], /) -> None: ...

    @property
    def vx(self) -> float: ...

    @vx.setter
    def vx(self, arg: float, /) -> None: ...

    @property
    def vy(self) -> float: ...

    @vy.setter
    def vy(self, arg: float, /) -> None: ...

    @property
    def vz(self) -> float: ...

    @vz.setter
    def vz(self, arg: float, /) -> None: ...

    @property
    def mx(self) -> float: ...

    @mx.setter
    def mx(self, arg: float, /) -> None: ...

    @property
    def my(self) -> float: ...

    @my.setter
    def my(self, arg: float, /) -> None: ...

    @property
    def mz(self) -> float: ...

    @mz.setter
    def mz(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(6))]: ...

    def __neg__(self) -> bivec4ds: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> bivec4ds: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> bivec4ds: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> mvec4ds_e: ...

    def __iadd__(self, arg: bivec4ds, /) -> bivec4ds: ...

    def __isub__(self, arg: bivec4ds, /) -> bivec4ds: ...

    def __eq__(self, arg: bivec4ds, /) -> bool: ...

    def __ne__(self, arg: bivec4ds, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> bivec4ds: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> bivec4ds: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> bivec4ds: ...

    def __rmul__(self, arg: float, /) -> bivec4ds: ...

    def __truediv__(self, arg: float, /) -> bivec4ds: ...

    def __imul__(self, arg: float, /) -> bivec4ds: ...

    def __itruediv__(self, arg: float, /) -> bivec4ds: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> bivec4ds: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> vec4ds: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> vec4ds: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> bivec4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> bivec4ds: ...

class dualnum4ds:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(2), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(2))]: ...

    def __neg__(self) -> dualnum4ds: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> dualnum4ds: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> dualnum4ds: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: mvec4ds_u, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> dualnum4ds: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> dualnum4ds: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: mvec4ds_u, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: mvec4ds, /) -> mvec4ds: ...

    def __iadd__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    def __isub__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    def __eq__(self, arg: dualnum4ds, /) -> bool: ...

    def __ne__(self, arg: dualnum4ds, /) -> bool: ...

    def __mul__(self, arg: float, /) -> dualnum4ds: ...

    def __rmul__(self, arg: float, /) -> dualnum4ds: ...

    def __truediv__(self, arg: float, /) -> dualnum4ds: ...

    def __imul__(self, arg: float, /) -> dualnum4ds: ...

    def __itruediv__(self, arg: float, /) -> dualnum4ds: ...

    def gr0(self) -> scalar4ds: ...

    def gr4(self) -> pscalar4ds: ...

class mvec4ds:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, arg8: float, arg9: float, arg10: float, arg11: float, arg12: float, arg13: float, arg14: float, arg15: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg: vec4ds, /) -> None: ...

    @overload
    def __init__(self, arg: bivec4ds, /) -> None: ...

    @overload
    def __init__(self, arg: trivec4ds, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4ds, arg1: bivec4ds, arg2: pscalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg: mvec4ds_e, /) -> None: ...

    @overload
    def __init__(self, arg0: vec4ds, arg1: trivec4ds, /) -> None: ...

    @overload
    def __init__(self, arg: mvec4ds_u, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4ds, arg1: vec4ds, arg2: bivec4ds, arg3: trivec4ds, arg4: pscalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(16), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    @property
    def c4(self) -> float: ...

    @c4.setter
    def c4(self, arg: float, /) -> None: ...

    @property
    def c5(self) -> float: ...

    @c5.setter
    def c5(self, arg: float, /) -> None: ...

    @property
    def c6(self) -> float: ...

    @c6.setter
    def c6(self, arg: float, /) -> None: ...

    @property
    def c7(self) -> float: ...

    @c7.setter
    def c7(self, arg: float, /) -> None: ...

    @property
    def c8(self) -> float: ...

    @c8.setter
    def c8(self, arg: float, /) -> None: ...

    @property
    def c9(self) -> float: ...

    @c9.setter
    def c9(self, arg: float, /) -> None: ...

    @property
    def c10(self) -> float: ...

    @c10.setter
    def c10(self, arg: float, /) -> None: ...

    @property
    def c11(self) -> float: ...

    @c11.setter
    def c11(self, arg: float, /) -> None: ...

    @property
    def c12(self) -> float: ...

    @c12.setter
    def c12(self, arg: float, /) -> None: ...

    @property
    def c13(self) -> float: ...

    @c13.setter
    def c13(self, arg: float, /) -> None: ...

    @property
    def c14(self) -> float: ...

    @c14.setter
    def c14(self, arg: float, /) -> None: ...

    @property
    def c15(self) -> float: ...

    @c15.setter
    def c15(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(16))]: ...

    def __neg__(self) -> mvec4ds: ...

    @overload
    def __add__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    def __iadd__(self, arg: mvec4ds, /) -> mvec4ds: ...

    def __isub__(self, arg: mvec4ds, /) -> mvec4ds: ...

    def __eq__(self, arg: mvec4ds, /) -> bool: ...

    def __ne__(self, arg: mvec4ds, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> mvec4ds: ...

    def __rmul__(self, arg: float, /) -> mvec4ds: ...

    def __truediv__(self, arg: float, /) -> mvec4ds: ...

    def __imul__(self, arg: float, /) -> mvec4ds: ...

    def __itruediv__(self, arg: float, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> mvec4ds: ...

    def gr0(self) -> scalar4ds: ...

    def gr1(self) -> vec4ds: ...

    def gr2(self) -> bivec4ds: ...

    def gr3(self) -> trivec4ds: ...

    def gr4(self) -> pscalar4ds: ...

class mvec4ds_e:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> None: ...

    @overload
    def __init__(self, arg: scalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg: bivec4ds, /) -> None: ...

    @overload
    def __init__(self, arg: pscalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4ds, arg1: bivec4ds, /) -> None: ...

    @overload
    def __init__(self, arg0: bivec4ds, arg1: pscalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4ds, arg1: pscalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg0: scalar4ds, arg1: bivec4ds, arg2: pscalar4ds, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(8), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    @property
    def c4(self) -> float: ...

    @c4.setter
    def c4(self, arg: float, /) -> None: ...

    @property
    def c5(self) -> float: ...

    @c5.setter
    def c5(self, arg: float, /) -> None: ...

    @property
    def c6(self) -> float: ...

    @c6.setter
    def c6(self, arg: float, /) -> None: ...

    @property
    def c7(self) -> float: ...

    @c7.setter
    def c7(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(8))]: ...

    def __neg__(self) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> mvec4ds_e: ...

    def __iadd__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    def __isub__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    def __eq__(self, arg: mvec4ds_e, /) -> bool: ...

    def __ne__(self, arg: mvec4ds_e, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    def __rmul__(self, arg: float, /) -> mvec4ds_e: ...

    def __truediv__(self, arg: float, /) -> mvec4ds_e: ...

    def __imul__(self, arg: float, /) -> mvec4ds_e: ...

    def __itruediv__(self, arg: float, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> mvec4ds_e: ...

    def gr0(self) -> scalar4ds: ...

    def gr2(self) -> bivec4ds: ...

    def gr4(self) -> pscalar4ds: ...

class mvec4ds_u:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float, /) -> None: ...

    @overload
    def __init__(self, arg: vec4ds, /) -> None: ...

    @overload
    def __init__(self, arg: trivec4ds, /) -> None: ...

    @overload
    def __init__(self, arg0: vec4ds, arg1: trivec4ds, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(8), order='C', device='cpu')], /) -> None: ...

    @property
    def c0(self) -> float: ...

    @c0.setter
    def c0(self, arg: float, /) -> None: ...

    @property
    def c1(self) -> float: ...

    @c1.setter
    def c1(self, arg: float, /) -> None: ...

    @property
    def c2(self) -> float: ...

    @c2.setter
    def c2(self, arg: float, /) -> None: ...

    @property
    def c3(self) -> float: ...

    @c3.setter
    def c3(self, arg: float, /) -> None: ...

    @property
    def c4(self) -> float: ...

    @c4.setter
    def c4(self, arg: float, /) -> None: ...

    @property
    def c5(self) -> float: ...

    @c5.setter
    def c5(self, arg: float, /) -> None: ...

    @property
    def c6(self) -> float: ...

    @c6.setter
    def c6(self, arg: float, /) -> None: ...

    @property
    def c7(self) -> float: ...

    @c7.setter
    def c7(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(8))]: ...

    def __neg__(self) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    def __iadd__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    def __isub__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    def __eq__(self, arg: mvec4ds_u, /) -> bool: ...

    def __ne__(self, arg: mvec4ds_u, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> mvec4ds_u: ...

    def __rmul__(self, arg: float, /) -> mvec4ds_u: ...

    def __truediv__(self, arg: float, /) -> mvec4ds_u: ...

    def __imul__(self, arg: float, /) -> mvec4ds_u: ...

    def __itruediv__(self, arg: float, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> mvec4ds_u: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> mvec4ds_u: ...

    def gr1(self) -> vec4ds: ...

    def gr3(self) -> trivec4ds: ...

class pscalar4ds:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> pscalar4ds: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> pscalar4ds: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> dualnum4ds: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> pscalar4ds: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> dualnum4ds: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    @overload
    def __mul__(self, arg: float, /) -> pscalar4ds: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> vec4ds: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> bivec4ds: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> trivec4ds: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> pscalar4ds: ...

    def __rmul__(self, arg: float, /) -> pscalar4ds: ...

    def __truediv__(self, arg: float, /) -> pscalar4ds: ...

    def __eq__(self, arg: pscalar4ds, /) -> bool: ...

    def __ne__(self, arg: pscalar4ds, /) -> bool: ...

    @overload
    def __lt__(self, arg: pscalar4ds, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: pscalar4ds, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: pscalar4ds, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: pscalar4ds, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> vec4ds: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> bivec4ds: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> trivec4ds: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> pscalar4ds: ...

class scalar4ds:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: float, /) -> None: ...

    @property
    def value(self) -> float: ...

    @value.setter
    def value(self, arg: float, /) -> None: ...

    def __float__(self) -> float: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __neg__(self) -> scalar4ds: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> dualnum4ds: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> dualnum4ds: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> dualnum4ds: ...

    @overload
    def __mul__(self, arg: float, /) -> scalar4ds: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> pscalar4ds: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> trivec4ds: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> bivec4ds: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> vec4ds: ...

    def __rmul__(self, arg: float, /) -> scalar4ds: ...

    def __truediv__(self, arg: float, /) -> scalar4ds: ...

    def __eq__(self, arg: scalar4ds, /) -> bool: ...

    def __ne__(self, arg: scalar4ds, /) -> bool: ...

    @overload
    def __lt__(self, arg: scalar4ds, /) -> bool: ...

    @overload
    def __lt__(self, arg: float, /) -> bool: ...

    @overload
    def __le__(self, arg: scalar4ds, /) -> bool: ...

    @overload
    def __le__(self, arg: float, /) -> bool: ...

    @overload
    def __gt__(self, arg: scalar4ds, /) -> bool: ...

    @overload
    def __gt__(self, arg: float, /) -> bool: ...

    @overload
    def __ge__(self, arg: scalar4ds, /) -> bool: ...

    @overload
    def __ge__(self, arg: float, /) -> bool: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> pscalar4ds: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> trivec4ds: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> bivec4ds: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> vec4ds: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> bivec4ds: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> vec4ds: ...

class trivec4ds:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C', device='cpu')], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def z(self) -> float: ...

    @z.setter
    def z(self, arg: float, /) -> None: ...

    @property
    def w(self) -> float: ...

    @w.setter
    def w(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(4))]: ...

    def __neg__(self) -> trivec4ds: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> trivec4ds: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> trivec4ds: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> mvec4ds_u: ...

    @overload
    def __sub__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    def __iadd__(self, arg: trivec4ds, /) -> trivec4ds: ...

    def __isub__(self, arg: trivec4ds, /) -> trivec4ds: ...

    def __eq__(self, arg: trivec4ds, /) -> bool: ...

    def __ne__(self, arg: trivec4ds, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> trivec4ds: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> vec4ds: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> trivec4ds: ...

    def __rmul__(self, arg: float, /) -> trivec4ds: ...

    def __truediv__(self, arg: float, /) -> trivec4ds: ...

    def __imul__(self, arg: float, /) -> trivec4ds: ...

    def __itruediv__(self, arg: float, /) -> trivec4ds: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> vec4ds: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> vec4ds: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> bivec4ds: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> trivec4ds: ...

class vec4ds:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, /) -> None: ...

    @overload
    def __init__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C', device='cpu')], /) -> None: ...

    @property
    def x(self) -> float: ...

    @x.setter
    def x(self, arg: float, /) -> None: ...

    @property
    def y(self) -> float: ...

    @y.setter
    def y(self, arg: float, /) -> None: ...

    @property
    def z(self) -> float: ...

    @z.setter
    def z(self, arg: float, /) -> None: ...

    @property
    def w(self) -> float: ...

    @w.setter
    def w(self, arg: float, /) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def __format__(self, format_spec: str = "") -> str: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> Annotated[NDArray[numpy.float64], dict(shape=(4))]: ...

    def __neg__(self) -> vec4ds: ...

    @overload
    def __add__(self, arg: vec4ds, /) -> vec4ds: ...

    @overload
    def __add__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __add__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __add__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: vec4ds, /) -> vec4ds: ...

    @overload
    def __sub__(self, arg: trivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __sub__(self, arg: mvec4ds_u, /) -> mvec4ds_u: ...

    @overload
    def __sub__(self, arg: scalar4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: bivec4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: pscalar4ds, /) -> mvec4ds: ...

    @overload
    def __sub__(self, arg: dualnum4ds, /) -> mvec4ds: ...

    def __iadd__(self, arg: vec4ds, /) -> vec4ds: ...

    def __isub__(self, arg: vec4ds, /) -> vec4ds: ...

    def __eq__(self, arg: vec4ds, /) -> bool: ...

    def __ne__(self, arg: vec4ds, /) -> bool: ...

    @overload
    def __mul__(self, arg: float, /) -> vec4ds: ...

    @overload
    def __mul__(self, arg: vec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __mul__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: pscalar4ds, /) -> trivec4ds: ...

    @overload
    def __mul__(self, arg: trivec4ds, /) -> mvec4ds_e: ...

    @overload
    def __mul__(self, arg: bivec4ds, /) -> mvec4ds_u: ...

    @overload
    def __mul__(self, arg: scalar4ds, /) -> vec4ds: ...

    def __rmul__(self, arg: float, /) -> vec4ds: ...

    def __truediv__(self, arg: float, /) -> vec4ds: ...

    def __imul__(self, arg: float, /) -> vec4ds: ...

    def __itruediv__(self, arg: float, /) -> vec4ds: ...

    @overload
    def __lshift__(self, arg: vec4ds, /) -> scalar4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __lshift__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __lshift__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __lshift__(self, arg: pscalar4ds, /) -> trivec4ds: ...

    @overload
    def __lshift__(self, arg: trivec4ds, /) -> bivec4ds: ...

    @overload
    def __lshift__(self, arg: bivec4ds, /) -> vec4ds: ...

    @overload
    def __lshift__(self, arg: scalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: vec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __rshift__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __rshift__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __rshift__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: trivec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: bivec4ds, /) -> scalar4ds: ...

    @overload
    def __rshift__(self, arg: scalar4ds, /) -> vec4ds: ...

    @overload
    def __xor__(self, arg: vec4ds, /) -> bivec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds, /) -> mvec4ds: ...

    @overload
    def __xor__(self, arg: mvec4ds_e, /) -> mvec4ds_u: ...

    @overload
    def __xor__(self, arg: mvec4ds_u, /) -> mvec4ds_e: ...

    @overload
    def __xor__(self, arg: pscalar4ds, /) -> scalar4ds: ...

    @overload
    def __xor__(self, arg: trivec4ds, /) -> pscalar4ds: ...

    @overload
    def __xor__(self, arg: bivec4ds, /) -> trivec4ds: ...

    @overload
    def __xor__(self, arg: scalar4ds, /) -> vec4ds: ...

def angle(arg0: vec4ds, arg1: vec4ds, /) -> float: ...

@overload
def cmt(arg0: mvec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def cmt(arg0: pscalar4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: pscalar4ds, arg1: trivec4ds, /) -> vec4ds: ...

@overload
def cmt(arg0: trivec4ds, arg1: pscalar4ds, /) -> vec4ds: ...

@overload
def cmt(arg0: pscalar4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: bivec4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: pscalar4ds, arg1: vec4ds, /) -> trivec4ds: ...

@overload
def cmt(arg0: vec4ds, arg1: pscalar4ds, /) -> trivec4ds: ...

@overload
def cmt(arg0: pscalar4ds, arg1: scalar4ds, /) -> pscalar4ds: ...

@overload
def cmt(arg0: scalar4ds, arg1: pscalar4ds, /) -> pscalar4ds: ...

@overload
def cmt(arg0: trivec4ds, arg1: trivec4ds, /) -> bivec4ds: ...

@overload
def cmt(arg0: trivec4ds, arg1: bivec4ds, /) -> trivec4ds: ...

@overload
def cmt(arg0: bivec4ds, arg1: trivec4ds, /) -> trivec4ds: ...

@overload
def cmt(arg0: trivec4ds, arg1: vec4ds, /) -> pscalar4ds: ...

@overload
def cmt(arg0: vec4ds, arg1: trivec4ds, /) -> pscalar4ds: ...

@overload
def cmt(arg0: trivec4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: scalar4ds, arg1: trivec4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: bivec4ds, arg1: bivec4ds, /) -> bivec4ds: ...

@overload
def cmt(arg0: bivec4ds, arg1: vec4ds, /) -> vec4ds: ...

@overload
def cmt(arg0: vec4ds, arg1: bivec4ds, /) -> vec4ds: ...

@overload
def cmt(arg0: bivec4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: scalar4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: vec4ds, arg1: vec4ds, /) -> bivec4ds: ...

@overload
def cmt(arg0: vec4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: scalar4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def cmt(arg0: scalar4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def conj(arg: scalar4ds, /) -> scalar4ds: ...

@overload
def conj(arg: vec4ds, /) -> vec4ds: ...

@overload
def conj(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def conj(arg: trivec4ds, /) -> trivec4ds: ...

@overload
def conj(arg: pscalar4ds, /) -> pscalar4ds: ...

@overload
def conj(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def conj(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def conj(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def dot(arg0: mvec4ds, arg1: mvec4ds, /) -> scalar4ds: ...

@overload
def dot(arg0: mvec4ds_e, arg1: mvec4ds_e, /) -> scalar4ds: ...

@overload
def dot(arg0: mvec4ds_u, arg1: mvec4ds_u, /) -> scalar4ds: ...

@overload
def dot(arg0: pscalar4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def dot(arg0: trivec4ds, arg1: trivec4ds, /) -> scalar4ds: ...

@overload
def dot(arg0: bivec4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def dot(arg0: vec4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def dot(arg0: scalar4ds, arg1: scalar4ds, /) -> scalar4ds: ...

def exp(arg: bivec4ds, /) -> mvec4ds_e: ...

def get_boost(arg0: bivec4ds, arg1: float, /) -> mvec4ds_e: ...

def get_rotor(arg0: bivec4ds, arg1: float, /) -> mvec4ds_e: ...

@overload
def gr_inv(arg: scalar4ds, /) -> scalar4ds: ...

@overload
def gr_inv(arg: vec4ds, /) -> vec4ds: ...

@overload
def gr_inv(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def gr_inv(arg: trivec4ds, /) -> trivec4ds: ...

@overload
def gr_inv(arg: pscalar4ds, /) -> pscalar4ds: ...

@overload
def gr_inv(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def gr_inv(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def gr_inv(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def inv(arg: scalar4ds, /) -> scalar4ds: ...

@overload
def inv(arg: vec4ds, /) -> vec4ds: ...

@overload
def inv(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def inv(arg: trivec4ds, /) -> trivec4ds: ...

@overload
def inv(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def inv(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def inv(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def is_congruent(arg0: scalar4ds, arg1: scalar4ds, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: vec4ds, arg1: vec4ds, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: bivec4ds, arg1: bivec4ds, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: trivec4ds, arg1: trivec4ds, arg2: float, /) -> bool: ...

@overload
def is_congruent(arg0: pscalar4ds, arg1: pscalar4ds, arg2: float, /) -> bool: ...

@overload
def is_lightlike(arg: vec4ds, /) -> bool: ...

@overload
def is_lightlike(arg: bivec4ds, /) -> bool: ...

@overload
def is_lightlike(arg: trivec4ds, /) -> bool: ...

@overload
def is_spacelike(arg: vec4ds, /) -> bool: ...

@overload
def is_spacelike(arg: bivec4ds, /) -> bool: ...

@overload
def is_spacelike(arg: trivec4ds, /) -> bool: ...

@overload
def is_timelike(arg: vec4ds, /) -> bool: ...

@overload
def is_timelike(arg: bivec4ds, /) -> bool: ...

@overload
def is_timelike(arg: trivec4ds, /) -> bool: ...

@overload
def l_cmpl(arg: scalar4ds, /) -> pscalar4ds: ...

@overload
def l_cmpl(arg: vec4ds, /) -> trivec4ds: ...

@overload
def l_cmpl(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def l_cmpl(arg: trivec4ds, /) -> vec4ds: ...

@overload
def l_cmpl(arg: pscalar4ds, /) -> scalar4ds: ...

@overload
def l_cmpl(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def l_cmpl(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def l_cmpl(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def l_dual(arg: scalar4ds, /) -> pscalar4ds: ...

@overload
def l_dual(arg: vec4ds, /) -> trivec4ds: ...

@overload
def l_dual(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def l_dual(arg: trivec4ds, /) -> vec4ds: ...

@overload
def l_dual(arg: pscalar4ds, /) -> scalar4ds: ...

@overload
def l_dual(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def l_dual(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def l_dual(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def normalize(arg: scalar4ds, /) -> scalar4ds: ...

@overload
def normalize(arg: vec4ds, /) -> vec4ds: ...

@overload
def normalize(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def normalize(arg: trivec4ds, /) -> trivec4ds: ...

@overload
def nrm(arg: scalar4ds, /) -> scalar4ds: ...

@overload
def nrm(arg: vec4ds, /) -> scalar4ds: ...

@overload
def nrm(arg: bivec4ds, /) -> scalar4ds: ...

@overload
def nrm(arg: trivec4ds, /) -> scalar4ds: ...

@overload
def nrm(arg: pscalar4ds, /) -> scalar4ds: ...

@overload
def nrm(arg: mvec4ds_e, /) -> scalar4ds: ...

@overload
def nrm(arg: mvec4ds_u, /) -> scalar4ds: ...

@overload
def nrm(arg: mvec4ds, /) -> scalar4ds: ...

@overload
def nrm_sq(arg: scalar4ds, /) -> float: ...

@overload
def nrm_sq(arg: vec4ds, /) -> float: ...

@overload
def nrm_sq(arg: bivec4ds, /) -> float: ...

@overload
def nrm_sq(arg: trivec4ds, /) -> float: ...

@overload
def nrm_sq(arg: pscalar4ds, /) -> float: ...

@overload
def nrm_sq(arg: mvec4ds_e, /) -> float: ...

@overload
def nrm_sq(arg: mvec4ds_u, /) -> float: ...

@overload
def nrm_sq(arg: mvec4ds, /) -> float: ...

@overload
def project_onto(arg0: vec4ds, arg1: vec4ds, /) -> vec4ds: ...

@overload
def project_onto(arg0: vec4ds, arg1: bivec4ds, /) -> vec4ds: ...

@overload
def r_cmpl(arg: scalar4ds, /) -> pscalar4ds: ...

@overload
def r_cmpl(arg: vec4ds, /) -> trivec4ds: ...

@overload
def r_cmpl(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def r_cmpl(arg: trivec4ds, /) -> vec4ds: ...

@overload
def r_cmpl(arg: pscalar4ds, /) -> scalar4ds: ...

@overload
def r_cmpl(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def r_cmpl(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def r_cmpl(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def r_dual(arg: scalar4ds, /) -> pscalar4ds: ...

@overload
def r_dual(arg: vec4ds, /) -> trivec4ds: ...

@overload
def r_dual(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def r_dual(arg: trivec4ds, /) -> vec4ds: ...

@overload
def r_dual(arg: pscalar4ds, /) -> scalar4ds: ...

@overload
def r_dual(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def r_dual(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def r_dual(arg: mvec4ds, /) -> mvec4ds: ...

def rapidity(arg0: vec4ds, arg1: vec4ds, /) -> float: ...

@overload
def reflect_on(arg0: vec4ds, arg1: vec4ds, /) -> vec4ds: ...

@overload
def reflect_on(arg0: vec4ds, arg1: trivec4ds, /) -> vec4ds: ...

@overload
def reflect_on(arg0: vec4ds, arg1: bivec4ds, /) -> vec4ds: ...

@overload
def reflect_on(arg0: bivec4ds, arg1: bivec4ds, /) -> bivec4ds: ...

def reflect_on_vec(arg0: vec4ds, arg1: vec4ds, /) -> vec4ds: ...

@overload
def reject_from(arg0: vec4ds, arg1: vec4ds, /) -> vec4ds: ...

@overload
def reject_from(arg0: vec4ds, arg1: bivec4ds, /) -> vec4ds: ...

def rel_bivec_split(arg0: bivec4ds, arg1: vec4ds, /) -> bivec4ds: ...

def rel_vec_split(arg0: bivec4ds, arg1: vec4ds, /) -> bivec4ds: ...

@overload
def rev(arg: scalar4ds, /) -> scalar4ds: ...

@overload
def rev(arg: vec4ds, /) -> vec4ds: ...

@overload
def rev(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def rev(arg: trivec4ds, /) -> trivec4ds: ...

@overload
def rev(arg: pscalar4ds, /) -> pscalar4ds: ...

@overload
def rev(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def rev(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def rev(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def rrev(arg: scalar4ds, /) -> scalar4ds: ...

@overload
def rrev(arg: vec4ds, /) -> vec4ds: ...

@overload
def rrev(arg: bivec4ds, /) -> bivec4ds: ...

@overload
def rrev(arg: trivec4ds, /) -> trivec4ds: ...

@overload
def rrev(arg: pscalar4ds, /) -> pscalar4ds: ...

@overload
def rrev(arg: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def rrev(arg: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def rrev(arg: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: mvec4ds_e, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: mvec4ds_u, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: pscalar4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: trivec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: trivec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: bivec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: bivec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: vec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def rwdg(arg0: mvec4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: mvec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: mvec4ds_e, /) -> mvec4ds_u: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: pscalar4ds, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: trivec4ds, /) -> mvec4ds_u: ...

@overload
def rwdg(arg0: trivec4ds, arg1: mvec4ds_e, /) -> mvec4ds_u: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: bivec4ds, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: bivec4ds, arg1: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: vec4ds, /) -> vec4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: mvec4ds_e, /) -> vec4ds: ...

@overload
def rwdg(arg0: mvec4ds_e, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: mvec4ds_e, /) -> scalar4ds: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: mvec4ds_u, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: pscalar4ds, /) -> mvec4ds_u: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: trivec4ds, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: trivec4ds, arg1: mvec4ds_u, /) -> mvec4ds_e: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: bivec4ds, /) -> vec4ds: ...

@overload
def rwdg(arg0: bivec4ds, arg1: mvec4ds_u, /) -> vec4ds: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: mvec4ds_u, /) -> scalar4ds: ...

@overload
def rwdg(arg0: mvec4ds_u, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: mvec4ds_u, /) -> scalar4ds: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: pscalar4ds, /) -> pscalar4ds: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: trivec4ds, /) -> trivec4ds: ...

@overload
def rwdg(arg0: trivec4ds, arg1: pscalar4ds, /) -> trivec4ds: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: bivec4ds, /) -> bivec4ds: ...

@overload
def rwdg(arg0: bivec4ds, arg1: pscalar4ds, /) -> bivec4ds: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: vec4ds, /) -> vec4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: pscalar4ds, /) -> vec4ds: ...

@overload
def rwdg(arg0: pscalar4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: trivec4ds, arg1: trivec4ds, /) -> bivec4ds: ...

@overload
def rwdg(arg0: trivec4ds, arg1: bivec4ds, /) -> vec4ds: ...

@overload
def rwdg(arg0: bivec4ds, arg1: trivec4ds, /) -> vec4ds: ...

@overload
def rwdg(arg0: trivec4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: trivec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: trivec4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: trivec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: bivec4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: bivec4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: bivec4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: vec4ds, arg1: scalar4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def rwdg(arg0: scalar4ds, arg1: scalar4ds, /) -> scalar4ds: ...

def space_split(arg0: vec4ds, arg1: vec4ds, /) -> bivec4ds: ...

def time_split(arg0: vec4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def transform(arg0: vec4ds, arg1: mvec4ds_e, /) -> vec4ds: ...

@overload
def transform(arg0: bivec4ds, arg1: mvec4ds_e, /) -> bivec4ds: ...

@overload
def transform(arg0: trivec4ds, arg1: mvec4ds_e, /) -> trivec4ds: ...

@overload
def transform(arg0: mvec4ds, arg1: mvec4ds_e, /) -> mvec4ds: ...

@overload
def transform_opt(arg0: vec4ds, arg1: mvec4ds_e, /) -> vec4ds: ...

@overload
def transform_opt(arg0: Sequence[vec4ds], arg1: mvec4ds_e, /) -> list[vec4ds]: ...

@overload
def wdg(arg0: mvec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds, arg1: mvec4ds_e, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds, arg1: mvec4ds_u, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds, arg1: pscalar4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: pscalar4ds, arg1: mvec4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: mvec4ds, arg1: trivec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds, arg1: bivec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: bivec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds, arg1: vec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: vec4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds, arg1: scalar4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: scalar4ds, arg1: mvec4ds, /) -> mvec4ds: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: mvec4ds_e, /) -> mvec4ds_u: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: pscalar4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: pscalar4ds, arg1: mvec4ds_e, /) -> pscalar4ds: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: trivec4ds, /) -> trivec4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: mvec4ds_e, /) -> trivec4ds: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: bivec4ds, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: bivec4ds, arg1: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: vec4ds, /) -> mvec4ds_u: ...

@overload
def wdg(arg0: vec4ds, arg1: mvec4ds_e, /) -> mvec4ds_u: ...

@overload
def wdg(arg0: mvec4ds_e, arg1: scalar4ds, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: scalar4ds, arg1: mvec4ds_e, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: mvec4ds_u, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: pscalar4ds, arg1: mvec4ds_u, /) -> scalar4ds: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: trivec4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: mvec4ds_u, /) -> pscalar4ds: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: bivec4ds, /) -> trivec4ds: ...

@overload
def wdg(arg0: bivec4ds, arg1: mvec4ds_u, /) -> trivec4ds: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: vec4ds, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: vec4ds, arg1: mvec4ds_u, /) -> mvec4ds_e: ...

@overload
def wdg(arg0: mvec4ds_u, arg1: scalar4ds, /) -> mvec4ds_u: ...

@overload
def wdg(arg0: scalar4ds, arg1: mvec4ds_u, /) -> mvec4ds_u: ...

@overload
def wdg(arg0: pscalar4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: pscalar4ds, arg1: trivec4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: pscalar4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: bivec4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: pscalar4ds, arg1: vec4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: vec4ds, arg1: pscalar4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: pscalar4ds, arg1: scalar4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: scalar4ds, arg1: pscalar4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: trivec4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: bivec4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: bivec4ds, arg1: trivec4ds, /) -> scalar4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: vec4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: vec4ds, arg1: trivec4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: trivec4ds, arg1: scalar4ds, /) -> trivec4ds: ...

@overload
def wdg(arg0: scalar4ds, arg1: trivec4ds, /) -> trivec4ds: ...

@overload
def wdg(arg0: bivec4ds, arg1: bivec4ds, /) -> pscalar4ds: ...

@overload
def wdg(arg0: bivec4ds, arg1: vec4ds, /) -> trivec4ds: ...

@overload
def wdg(arg0: vec4ds, arg1: bivec4ds, /) -> trivec4ds: ...

@overload
def wdg(arg0: bivec4ds, arg1: scalar4ds, /) -> bivec4ds: ...

@overload
def wdg(arg0: scalar4ds, arg1: bivec4ds, /) -> bivec4ds: ...

@overload
def wdg(arg0: vec4ds, arg1: vec4ds, /) -> bivec4ds: ...

@overload
def wdg(arg0: vec4ds, arg1: scalar4ds, /) -> vec4ds: ...

@overload
def wdg(arg0: scalar4ds, arg1: vec4ds, /) -> vec4ds: ...

@overload
def wdg(arg0: scalar4ds, arg1: scalar4ds, /) -> scalar4ds: ...

I_4ds: pscalar4ds = ...

I_4ds_mv: mvec4ds = ...

I_4ds_mv_e: mvec4ds_e = ...

g1234_4ds: pscalar4ds = ...

g123_4ds: trivec4ds = ...

g123_4ds_mv: mvec4ds = ...

g124_4ds: trivec4ds = ...

g124_4ds_mv: mvec4ds = ...

g12_4ds: bivec4ds = ...

g12_4ds_mv: mvec4ds = ...

g12_4ds_mv_e: mvec4ds_e = ...

g14_4ds: bivec4ds = ...

g14_4ds_mv: mvec4ds = ...

g14_4ds_mv_e: mvec4ds_e = ...

g1_4ds: vec4ds = ...

g1_4ds_mv: mvec4ds = ...

g234_4ds: trivec4ds = ...

g234_4ds_mv: mvec4ds = ...

g23_4ds: bivec4ds = ...

g23_4ds_mv: mvec4ds = ...

g23_4ds_mv_e: mvec4ds_e = ...

g24_4ds: bivec4ds = ...

g24_4ds_mv: mvec4ds = ...

g24_4ds_mv_e: mvec4ds_e = ...

g2_4ds: vec4ds = ...

g2_4ds_mv: mvec4ds = ...

g314_4ds: trivec4ds = ...

g314_4ds_mv: mvec4ds = ...

g31_4ds: bivec4ds = ...

g31_4ds_mv: mvec4ds = ...

g31_4ds_mv_e: mvec4ds_e = ...

g34_4ds: bivec4ds = ...

g34_4ds_mv: mvec4ds = ...

g34_4ds_mv_e: mvec4ds_e = ...

g3_4ds: vec4ds = ...

g3_4ds_mv: mvec4ds = ...

g4_4ds: vec4ds = ...

g4_4ds_mv: mvec4ds = ...

one_4ds: scalar4ds = ...

one_4ds_mv: mvec4ds = ...

one_4ds_mv_e: mvec4ds_e = ...

t_dir_4ds: vec4ds = ...

x_dir_4ds: vec4ds = ...

y_dir_4ds: vec4ds = ...

z_dir_4ds: vec4ds = ...
